---
title: "Tracking ecosystem shifts, from microbes to mammals, with environmental DNA"
author: "Djurhuus et al."
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(include = FALSE)
library(here); library(plyr); library(biomformat); library(tidyverse); library(phyloseq); library(vegan); library(reshape2); library(MASS); library(stringr); library(purrr); library(ggplot2); library(Hmisc); library(lubridate); library(corrplot); library(gplots); library(rafalib);library(tissuesGeneExpression); library(genefilter); library(RColorBrewer); library(ggdendro);library(ComplexHeatmap); library(circlize); library(colorspace); library(GetoptLong);library(WGCNA); library(matrixStats);library(Hmisc); library(splines);library(foreach);library(doParallel);library(fastcluster); library(dynamicTreeCut); library(survival); library(WGCNA); library(cluster); library(beepr);library(bioDist); library(FactoMineR);library(MASS); library(ggfortify); library(factoextra); library(qpcR);library(mixOmics); library(flashClust); library(ggridges); library(plotly); library(randomForest)
```

```{r, include=FALSE}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7","red","grey", "grey20")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

add.alpha <- function(col, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
                     function(x) 
                       rgb(x[1], x[2], x[3], alpha=alpha))  
}
cbbPalette_alpha <- add.alpha(cbbPalette, alpha=0.5)

pal <- colorRampPalette(brewer.pal(11, "RdYlGn"))(50)
```

```{r read in MB data undergone decontamination, include=FALSE}
MB_16S_m2w <- merge_phyloseq(otu_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/16S/MB_16S_otu_table.csv", row.names = 1,check.names = FALSE)), taxa_are_rows = TRUE),tax_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/16S/MB_16S_tax_table.csv", row.names = 1))),sample_data(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/16S/MB_16S_sam_table.csv", row.names = 1)))

MB_18S_m2w <- merge_phyloseq(otu_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/18S/MB_18S_otu_table.csv", row.names = 1,check.names = FALSE)), taxa_are_rows = TRUE),tax_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/18S/MB_18S_taxa_table.csv", row.names = 1))),sample_data(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/18S/MB_18S_sam_table.csv", row.names = 1)))

MB_COI_m2w <- merge_phyloseq(otu_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/COI/MB_COI_otu_table.csv", row.names = 1,check.names = FALSE)), taxa_are_rows = TRUE),tax_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/COI/MB_COI_taxa_table.csv", row.names = 1))),sample_data(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/COI/MB_COI_sam_table.csv", row.names = 1)))

MB_12S_m2w <- merge_phyloseq(otu_table(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/12S/MB_12S_otu_table.csv", row.names = 1, check.names = FALSE), taxa_are_rows = TRUE), tax_table(as.matrix(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/12S/MB_12S_taxa_table.csv", row.names = 1))), sample_data(read.csv(file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/12S/MB_12S_sam_data.csv",row.names = 1)))
```

```{r functions for splitting species, adding taxonomy to highest level available and pseudoautocorrelation, include=FALSE,message=FALSE, warning=FALSE}
split_species = function(string, n = 2) {
  splits = str_split(string, "/", n + 1)
  res = map_if(splits, ~length(.x) > 2, ~.x[1:n]) %>%
    map_chr(str_c, collapse = "/")
  return(res)
}

add_taxonomy_column = function(physeq, num_species = 2) {
  tax_df = as.data.frame(tax_table(physeq)) %>%
    rownames_to_column("OTU") %>%
    mutate(Rank7 = split_species(Rank7, n = num_species)) %>%
    mutate(Taxonomy =
             case_when(
               is.na(Rank5)  ~ str_c("o:", Rank4),
               is.na(Rank6)   ~ str_c("f:", Rank5),
               is.na(Rank7) ~ str_c("g:", Rank6)
             )
    )
  
  tax = as.matrix(tax_df[, -1])
  rownames(tax) = tax_df$OTU
  tax_table(physeq) = tax_table(tax)
  
  return(physeq)
}

add_taxonomy_column2 = function(physeq, num_species = 2) {
  tax_df = as.data.frame(tax_table(physeq)) %>%
    rownames_to_column("OTU") %>%
    mutate(Rank7 = split_species(Rank7, n = num_species)) %>%
    mutate(Taxonomy2 =
             case_when(
               is.na(Taxonomy)   ~ str_c("c:", Rank3),
               is.na(Rank6)   ~ str_c(Taxonomy)             
             )
    )
  
  tax = as.matrix(tax_df[, -1])
  rownames(tax) = tax_df$OTU
  tax_table(physeq) = tax_table(tax)
  
  return(physeq)
}

add_taxonomy_column3 = function(physeq, num_species = 2) {
  tax_df = as.data.frame(tax_table(physeq)) %>%
    rownames_to_column("OTU") %>%
    mutate(Rank7 = split_species(Rank7, n = num_species)) %>%
    mutate(Taxonomy3 =
             case_when(
               is.na(Taxonomy2)   ~ str_c("p:", Rank2),
               is.na(Rank6)   ~ str_c(Taxonomy2)             
             )
    )
  
  tax = as.matrix(tax_df[, -1])
  rownames(tax) = tax_df$OTU
  tax_table(physeq) = tax_table(tax)
  
  return(physeq)
}

PA<-function(OTUs, DATES, REFERENCE = 1, METHOD = "euclidian"){

  #library(vegan,verbose = F)
  
  #order(DATES) #make sure these are in chronological order; enforce this rule by re-ordering, like so:
  OTUs<-OTUs[,order(DATES)]
  DATES<-sort(DATES)
  
  referenceTimePoint<-unique(DATES)[REFERENCE] #set a reference time point at a particular sample
  dayVector<-as.numeric(DATES-DATES[match(referenceTimePoint, DATES)]) #time difference in days, relative to reference point
  
  bcdist<-as.matrix(vegan::vegdist(t(OTUs), method=METHOD)) 
    diag(bcdist)<-NA   #don't count self-comparison within replicates
  
    distFUN <- function(x) as.vector(bcdist[DATES==x,DATES==referenceTimePoint]) #function to pull selected distances from matrix
  
  dist.res<-lapply(X=unique(DATES), FUN=distFUN)
    #dist.res<-as.data.frame(t(plyr::ldply(dist.res, rbind)))
    	maxlength<-max(sapply(dist.res, length))		
		for(i in 1:length(dist.res)){length(dist.res[[i]])<-maxlength}	#pad to create even columns
	  dist.res<-as.data.frame(dist.res, check.names=FALSE)	
    names(dist.res)<-unique(dayVector)
    
  return(dist.res)  
  
}

OneStep<-function(OTUs, DATES, METHOD = "euclidian"){
  
  #order(DATES) #make sure these are in chronological order; enforce this rule by re-ordering, like so:
  OTUs<-OTUs[,order(DATES)]
  DATES<-sort(DATES)
  
  dayVector<-as.numeric(unique(DATES)[2:length(unique(DATES))])-
  	as.numeric(unique(DATES)[1:(length(unique(DATES))-1)]) #time difference in days, relative to previous sample

  bcdist<-as.matrix(vegan::vegdist(t(OTUs), method=METHOD)) 
    diag(bcdist)<-NA   #don't count self-comparison within replicates
  
    distFUN <- function(x) as.vector(bcdist[DATES==unique(DATES)[x], DATES==unique(DATES)[x+1]]) #function to pull selected distances from matrix

  dist.res<-lapply(1:(length(unique(DATES))-1), FUN=distFUN)
     	maxlength<-max(sapply(dist.res, length))		
		for(i in 1:length(dist.res)){length(dist.res[[i]])<-maxlength}	#pad to create even columns
	  dist.res<-as.data.frame(dist.res, check.names=FALSE)	
    names(dist.res)<-paste("Step", 1:(length(unique(DATES))-1), dayVector, "Days", sep="_")
   
  return(dist.res) 
}


multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


strong.corrs.plot <- function(z, 
                              cutoff = 0.6, 
                              trophicLevels = trophic$trophic_fv[match(colnames(z), trophic$taxa)],
                              plotcount = 0) {  #for dataframe z, cutoff value of critical tau, and defined trophic levels (for color)

  #optional function to define colors to be used
  gg_color <- function(n, alpha = 0.5) {
    hues = seq(15, 375, length = n + 1)
    hcl(h = hues, l = 65, c = 100, alpha = alpha)[1:n]
  }
  trophicColors <- RColorBrewer::brewer.pal(length(unique(trophicLevels)), "YlGnBu")[match(trophicLevels, unique(trophicLevels))]
  #trophicColors <- gg_color(length(unique(trophicLevels)))[match(trophicLevels, unique(trophicLevels))]
  
  trophic.yvec <- unlist(lapply(1:ncol(z), function(w){rep(trophicColors[w], times = (ncol(z)-w))}))  
  trophic.xvec <- unlist(lapply(2:ncol(z), function(w){trophicColors[w:ncol(z)]}))
  
panel.cor <- function(x, y)
{
  plotcount <<- plotcount + 1
    #usr <- par("usr"); on.exit(par(usr))
    #par(usr = c(0, 1, 0, 1))
	if(abs(cor(x,y, method = "kendall"))<cutoff) NULL else {
	           ll <- par("usr") 
            	  polygon(c(ll[1],ll[2],ll[2]), 
            	          c(ll[3], ll[4],ll[3]), 
            	          border = NA, col = trophic.xvec[plotcount])
            	  polygon(c(ll[1],ll[2],ll[1]), 
            	          c(ll[3], ll[4],ll[4]), 
            	          border = NA, col = trophic.yvec[plotcount])
            	  points(y ~ x, pch = 19)}
  }

panel.smooth.cor <- function (x, y, col = par("col"), bg = NA, pch = par("pch"), 
    cex = 1, col.smooth = "steelblue1", span = .9, iter = 3, ...) 
{
    if (abs(cor(x, y, method = "kendall"))<cutoff) NULL else {
		    points(x, y, pch = pch, col = col, bg = bg, cex = cex)
		    ok <- is.finite(x) & is.finite(y)
		    if (any(ok)) 
		        lines(stats::lowess(x[ok], y[ok], f = span, iter = iter), 
		            col = col.smooth, lwd = 2, ...)    	
    }
}

diag.count<-0
mydiag.panel <- function(x, ...){
  diag.count<<-diag.count+1
    ll <- par("usr") 
  rect(ll[1], ll[3], ll[2], ll[4], col=trophicColors[diag.count]) 
  }


pairs(z, 
      lower.panel = panel.smooth.cor, 
      upper.panel = panel.cor, 
      diag.panel = mydiag.panel, 
      label.pos = 0.5, 
      labels = sapply(colnames(z), function(w) strsplit(w, ":")[[1]][2]),
      cex.labels = 0.9
      )

}

```

```{r transform sample abundance to proportion and make one dataframe per location, include=FALSE, echo=FALSE, warning=FALSE}
MB_16S_fam <- tax_glom(MB_16S_m2w, "Rank5")
MB_18S_fam <- tax_glom(MB_18S_m2w, "Rank5")
MB_COI_fam <- tax_glom(MB_COI_m2w, "Rank5")
MB_12S_fam <- tax_glom(MB_12S_m2w, "Rank5")

tax_table(MB_16S_fam) <- gsub('f_', as.character(NA), gsub('o_', as.character(NA), gsub('c_',as.character(NA), gsub('p_', as.character(NA),gsub('unknown', as.character(NA), tax_table(MB_16S_fam))))))
MB_16S_fam <- add_taxonomy_column(MB_16S_fam)
MB_16S_fam <- add_taxonomy_column2(MB_16S_fam)
MB_16S_fam <- subset_taxa(MB_16S_fam,Taxonomy2 !="NA")
MB_16S_fam <- tax_glom(MB_16S_fam,"Taxonomy2")
taxa_names(MB_16S_fam) <- paste(MB_16S_fam@tax_table[,9])
MB_16S_prop = transform_sample_counts(MB_16S_fam,function(x) x / sum(x))
MB_16S_prop = prune_taxa(taxa_sums(MB_16S_prop)>0, MB_16S_prop)
MB_16S_prop2 <- sweep(MB_16S_prop@otu_table,1,rowMaxs(MB_16S_prop@otu_table),"/")

#write.csv(as.data.frame(MB_16S_prop@tax_table), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/16S/MB_16S_tax_table.csv")  #is this the best way to save biom files?

tax_table(MB_18S_fam) <- gsub('f_', as.character(NA), gsub('o_', as.character(NA), gsub('c_',as.character(NA), gsub('p_', as.character(NA), gsub('unknown', as.character(NA),tax_table(MB_18S_fam))))))
MB_18S_fam <- add_taxonomy_column(MB_18S_fam)
MB_18S_fam <- add_taxonomy_column2(MB_18S_fam)
MB_18S_fam <- subset_taxa(MB_18S_fam,Taxonomy2 !="NA")
MB_18S_fam <- tax_glom(MB_18S_fam,"Taxonomy2")
taxa_names(MB_18S_fam) <- paste(MB_18S_fam@tax_table[,9])
MB_18S_prop = transform_sample_counts(MB_18S_fam,function(x) x / sum(x))
MB_18S_prop = prune_taxa(taxa_sums(MB_18S_prop)>0, MB_18S_prop)
MB_18S_prop2 <- sweep(MB_18S_prop@otu_table,1,rowMaxs(MB_18S_prop@otu_table),"/")

#write.csv(as.data.frame(MB_18S_prop@tax_table), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/18S/MB_18S_tax_table.csv")  #is this the best way to save biom files?

tax_table(MB_COI_fam) <- gsub('f_', as.character(NA), gsub('o_', as.character(NA), gsub('c_',as.character(NA), gsub('p_', as.character(NA), gsub('unknown', as.character(NA),tax_table(MB_COI_fam))))))
MB_COI_fam <- add_taxonomy_column(MB_COI_fam)
MB_COI_fam <- add_taxonomy_column2(MB_COI_fam)
MB_COI_fam <- subset_taxa(MB_COI_fam,Taxonomy2 !="NA")
MB_COI_fam <- tax_glom(MB_COI_fam,"Taxonomy2")
taxa_names(MB_COI_fam) <- paste(MB_COI_fam@tax_table[,9])
MB_COI_prop = transform_sample_counts(MB_COI_fam,function(x) x / sum(x))
MB_COI_prop = prune_taxa(taxa_sums(MB_COI_prop)>0, MB_COI_prop)
MB_COI_prop2 <- sweep(MB_COI_prop@otu_table,1,rowMaxs(MB_COI_prop@otu_table),"/")

#write.csv(as.data.frame(MB_COI_prop@tax_table), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/COI/MB_COI_tax_table.csv")  #is this the best way to save biom files?

tax_table(MB_12S_fam) <- gsub('f_', as.character(NA), gsub('o_', as.character(NA), gsub('c_',as.character(NA), gsub('p_', as.character(NA), gsub('unknown', as.character(NA),tax_table(MB_12S_fam))))))
MB_12S_fam <- add_taxonomy_column(MB_12S_fam) # Add family and order assignments 
MB_12S_fam <- add_taxonomy_column2(MB_12S_fam) # Add class and phylum assignments
MB_12S_fam <- subset_taxa(MB_12S_fam,Taxonomy2 !="NA") #get rid of all NAs in dataset.
taxa_names(MB_12S_fam) <- paste(MB_12S_fam@tax_table[,9])
MB_12S_prop = transform_sample_counts(MB_12S_fam,function(x) x / sum(x))
MB_12S_prop = prune_taxa(taxa_sums(MB_12S_prop)>0, MB_12S_prop)
MB_12S_prop2 <- sweep(MB_12S_prop@otu_table,1,rowMaxs(MB_12S_prop@otu_table),"/")

#write.csv(as.data.frame(MB_12S_prop@tax_table), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/12S/MB_12S_tax_table.csv")
#Merge all data from MB not relative abundance
MB_all_tax_ps <- merge_phyloseq(MB_COI_fam@otu_table, MB_16S_fam@otu_table,
                                MB_12S_fam@otu_table, MB_18S_fam@otu_table, MB_18S_fam@sam_data)

#Merge all OTU and taxa data from MB relative abundance. ps stands for phyloseq object, ts is for transformed
MB_all_tax_ps_ts <- merge_phyloseq(otu_table(MB_COI_prop2,taxa_are_rows = T),otu_table(MB_16S_prop2,taxa_are_rows = T), otu_table(MB_12S_prop2,taxa_are_rows = TRUE),otu_table(MB_18S_prop2,taxa_are_rows = TRUE), MB_18S_fam@sam_data) #merge data on previously transformed data.

# merge replicates for fun... 
MB_all_tax_ps_ts_merge <- merge_samples(MB_all_tax_ps_ts,"SAMPLING_date",fun=mean) #merge samples

#a <- MB_all_tax_ps_ts@sam_data
# filter out bad taxa 
badTaxa_MB <- read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/MB_badtaxa.csv", header=FALSE)
badTaxa_MB <- badTaxa_MB[[1]] # make bad taxa into list
goodTaxa_MB <- setdiff(taxa_names(MB_all_tax_ps_ts), badTaxa_MB) #subset good taxa
MB_all_tax_ps_rel = prune_taxa(goodTaxa_MB,MB_all_tax_ps_ts) #filter good taxa from all taxa list from all data (not merged replicates)
goodTaxa_MB_merge <- setdiff(taxa_names(MB_all_tax_ps_ts_merge), badTaxa_MB) #subset good taxa from merged replicates
MB_all_tax_ps_ts_merge = prune_taxa(goodTaxa_MB_merge,MB_all_tax_ps_ts_merge) # filter out good taxa from merged replicates
MB_merged_otu <- t(as.matrix(MB_all_tax_ps_ts_merge@otu_table)) #transpose merged otu table
#Divide all rows (taxa) with row max on transposed data
MB_merged_otu_table <- sweep(MB_merged_otu,1,rowMaxs(MB_merged_otu),"/") 
MB_all_merge <- as.data.frame(t(MB_merged_otu_table)) #create non transposed otu table

#saveRDS(MB_all_tax_ps_rel, "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_all_tax_ps_rel.Rdata")  
MB_all_otu_table <- as.matrix(MB_all_tax_ps_rel@otu_table)
MB_all_otu_table <- sweep(MB_all_otu_table,1,rowMaxs(MB_all_otu_table),"/")
MB_all_tax_ps_rel <- merge_phyloseq(otu_table(MB_all_otu_table, taxa_are_rows = TRUE), MB_all_tax_ps_rel@sam_data)

write.csv(MB_all_otu_table, "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_all_otu_table.csv")  
write.csv(MB_merged_otu_table, "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_merged_otu_table.csv")  
```

```{r filter by Kendall correlations, include=FALSE, echo =FALSE}
bit=function(x){print(x[c(1:10),c(1:10)]); print(dim(x))}  #shows top-left corner of a data.frame/matrix; useful for large datasets
colMax <- function(data) sapply(data, max, na.rm = TRUE) #get column-wise maximum value
Col2RN<-function(df, x){row.names(df)<-df[,x]; df<-df[-x]; return(df)} #convert column to row.names

# a<-readRDS("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MB_all_tax_ps_rel.Rdata")
# 
# otus<-as.data.frame(otu_table(a))
#   names(otus)
# meta<-as.data.frame(sample_data(a))
#   names(otus)<-meta$collection_date

otus<-MB_merged_otu_table
  
  #filter by sd or some other measure of variance
otus <- otus[specnumber(otus) > 1 , ]  #must occur in at least 2 time points, with zero abundance being a real data point in this case 

#compute CORRELATION after transposing dataset
corMB <- cor(t(otus), method = "kendall")

#save as dataframe and reshape; useful for plotting
corMB[lower.tri(corMB, T)] <- NA
corMB <- melt(corMB)%>%
  filter(!is.na(value))%>%
  filter(value>=0.7)

length(unique(unlist(corMB[,1:2])))  #339 unique taxa
    
    #save(corMB, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/analysis/MBKendall.Rdata")
    
    #sanity check plot
#    plot(otus["f:Paracalanidae",]~otus["f:Thalassiosiraceae",])
#    plot(otus["f:Carangidae",]~otus["f:Otariidae",])
   
unique_kend_taxa <- as.character(unique(unlist(corMB[,1:2])))
MB_merge_filt = prune_taxa(unique_kend_taxa,otu_table(MB_merged_otu_table, taxa_are_rows = TRUE))
#a <- MB_merge_filt@.Data
MB_all_filt = prune_taxa(unique_kend_taxa,otu_table(MB_all_tax_ps_rel, taxa_are_rows = TRUE))
write.csv(as.data.frame(MB_all_filt@.Data), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_all_filt.csv")
write.csv(as.data.frame(MB_merge_filt@.Data), "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_merge_filt.csv")
```

###Network analysis
```{r network analysis, echo=FALSE, message=FALSE, warning=FALSE}
options(stringsAsFactors = FALSE);
MB_Data <- as.matrix(MB_merge_filt)
dim(MB_Data);
#names(MB_Data);
datExpr0_MB = t(MB_Data) #transpose

#check if all taxa have good data (no zero variance datapoints and too many missing values)
gsg = goodSamplesGenes(datExpr0_MB, verbose = 3);
gsg$allOK

#run if not all taxa are ok!
if (!gsg$allOK)
{
  # Optionally, print the gene and sample names that were removed:
  if (sum(!gsg$goodGenes)>0) 
    printFlush(paste("Removing genes:", paste(names(datExpr0_MB)[!gsg$goodGenes], collapse = ", ")));
  if (sum(!gsg$goodSamples)>0) 
    printFlush(paste("Removing samples:", paste(rownames(datExpr0_MB)[!gsg$goodSamples], collapse = ", ")));
  # Remove the offending genes and samples from the data:
  datExpr0_MB = datExpr0_MB[gsg$goodSamples, gsg$goodGenes]
}

datExpr_MB <- datExpr0_MB
#make tree of samples to visualize any obvious outliers
sampleTree_MB = hclust(tau.dist(datExpr_MB))
#sizeGrWindow(12,9)
par(cex = 0.6);
#par(mar = c(0,4,2,0))
#pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/net_dendro_tau.pdf")
plot(sampleTree_MB, main="",sub="", xlab="", cex=0.7,cex.lab = 0.8, cex.axis = 0.7)
#dev.off()

nGenes_MB = ncol(datExpr_MB)
nSamples_MB = nrow(datExpr_MB)

#load trait data
traitData_MB = read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/metadata_MB_merged_sam.csv")
#dim(traitData_MB)
#names(traitData_MB)

# remove columns that hold information we do not need.
meta = as.data.frame(traitData_MB[, c(18,47,48,49,51,52)])
#meta = allTraits_MB[, -c(1)]
#datExpr_MB <- t(datExpr_MB)
# Form a data frame analogous to expression data that will hold the traits.
Samples_MB = rownames(datExpr_MB)
traitRows_MB = match(Samples_MB, traitData_MB$collection_date);
rownames(meta) = Samples_MB
datTraits_MB = meta
collectGarbage();

sampleTree2_MB = hclust(tau.dist(datExpr_MB), method = "average")
# Convert traits to a color representation: white means low, red means high, grey means missing entry
traitColors_MB = numbers2colors(scale(datTraits_MB), signed = FALSE);
# Plot the sample dendrogram and the colors underneath.
#pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/net_dendro_tau_w_env.pdf")
plotDendroAndColors(sampleTree2_MB, traitColors_MB,
                    groupLabels = names(datTraits_MB), 
                    main = "Sample dendrogram and trait heatmap")
#dev.off()

#STEP 2
allowWGCNAThreads()

# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=50, by=2))
# Call the network topology analysis function
sft_MB = pickSoftThreshold(datExpr_MB, powerVector = powers, verbose = 5)
# Plot the results:

#sizeGrWindow(9, 5)
#pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/pick_soft_threshold.pdf")
par(mfrow = c(1,2));
cex1 = 0.8;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft_MB$fitIndices[,1], -sign(sft_MB$fitIndices[,3])*sft_MB$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft_MB$fitIndices[,1], -sign(sft_MB$fitIndices[,3])*sft_MB$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.8,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft_MB$fitIndices[,1], sft_MB$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft_MB$fitIndices[,1], sft_MB$fitIndices[,5], labels=powers, cex=cex1,col="red")
#dev.off()

#create modules
#Choose power based on what the soft threshold results look like, ours are showing a scale free topography at around 22. See figs above.
A = adjacency(datExpr_MB, power = 22, type="unsigned")

# Digression: to define a signed network choose A =
# adjacency(datExprFemale, power = 12, type='signed')
# define a dissimilarity based on the topological overlap
dissTOM = TOMdist(A)
geneTree = hclust(tau.dist(dissTOM), method = "average")
plot(geneTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
# here we define the modules by cutting branches
moduleLabelsManual1 = cutreeDynamic(dendro = geneTree, distM = dissTOM, method = "hybrid",deepSplit = 2, pamRespectsDendro = F, minClusterSize = 30)

# Convert labels to colors for plotting
moduleColorsManual2 = labels2colors(moduleLabelsManual1)
moduleColors_MB = gsub("yellow","#ffc425", gsub("blue","#00aedb", gsub("green","#00b159", gsub("brown","#f37735", gsub("turquoise","#8c8c8c",gsub("grey","black", moduleColorsManual2))))))

pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/taxa_dendro_modules.pdf", height=7,width=10)
plotDendroAndColors(geneTree, moduleColors_MB,
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
dev.off()

MEList = moduleEigengenes(datExpr_MB, colors = moduleColors_MB)
MEs = MEList$eigengenes
# Add the weight to existing module eigengenes
MET=MEs
#MET = orderMEs(cbind(MEs, datTraits_MB$temp,datTraits_MB$chlorophyll))
colnames(MET) = c("blue", "green","grey","yellow","orange", "black")
# Plot the relationships among the eigengenes and the trait
plotEigengeneNetworks(MET, "",marDendro = c(0, 4, 1, 2), marHeatmap = c(3,4, 1, 2), cex.lab = 0.6, xLabelsAngle = 90)

pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/dendro_modules.pdf", height=2)
par(cex = 0.7)
plotEigengeneNetworks(MET, "",marDendro = c(0,4,2,0),plotHeatmaps = FALSE, signed=FALSE)
dev.off()

signif(cor(MET, use="p"), 2)
dissimME=(1-cor(MET, method="p"))/2
hclustdatME=hclust(tau.dist(dissimME), method="average" )
# Plot the eigengene dendrogram
par(mfrow=c(1,1))
plot(hclustdatME, main="Clustering tree based on the module eigengenes")
plotMEpairs(MET)

moduleTraitCor_MB = cor(MET, datTraits_MB, use = "p", method="spearman");
moduleTraitPvalue_MB = corPvalueStudent(moduleTraitCor_MB, nSamples_MB);
a <- p.adjust(moduleTraitPvalue_MB, method="holm", n=36)

# Will display correlations and their p-values
textMatrix_MB =  paste(signif(moduleTraitCor_MB, 2), "\n(",
                       signif(moduleTraitPvalue_MB, 1), ")", sep = "");
dim(textMatrix_MB) = dim(moduleTraitCor_MB)
# Display the correlation values within a heatmap plot
#pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/module_cor_envir.pdf")
#par(mar = c(6, 8.5, 3, 3));
#reorder <- c("yellow", "green","orange","black","blue", "grey")
#moduleTraitCor_MB %>%
#  mutate(moduleTraitCor_MB[,1] =  factor(moduleTraitCor_MB[,1], levels = reorder)) %>% arrange(moduleTraitCor_MB[,1])

pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/network/module_cor_envir.pdf")
labeledHeatmap(Matrix = moduleTraitCor_MB,
               xLabels = c("Upwelling","Temperature","Salinity","Chl. a","Nitrate","Diss. Oxygen"),
               yLabels = names(MET),
               yColorLabels = TRUE,
               ySymbols = names(MET),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               setStdMargins = FALSE,
               cex.text = 0.5,
               naColor = "grey",
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
dev.off()

#pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/heatmap_all_modules.pdf", height=12, width=15)
# par(mfrow=c(3,2), mar=c(1, 5, 5, 3))
# which.module="#ffc425"; #yellow
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
# which.module="#00aedb"; #blue
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
# which.module="#00b159" #green
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
# which.module="#f37735"; #orange
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
# which.module="#8c8c8c"; #dark grey
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
# which.module="black"; #grey
# plotMat(t(scale(datExpr_MB[,moduleColors_MB==which.module])),nrgcols=50,rlabels=colnames(datExpr_MB[,moduleColors_MB==which.module]),clabels=rownames(datExpr_MB),rcols=which.module)
color = c("#ffc425","#00aedb","#00b159","#f37735","#8c8c8c","black")

yel_rich <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="#ffc425"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(yel_rich) <- "yellow"
blue_rich <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="#00aedb"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(blue_rich) <- "blue"
green_rich <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="#00b159"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(green_rich) <- "green"
orange_rich <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="#f37735"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(orange_rich) <- "orange"
dg_rich <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="#8c8c8c"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(dg_rich) <- "dg"
black <- t(estimate_richness(t(otu_table(round(as((otu_table(datExpr_MB[,moduleColors_MB=="black"])), "matrix")), taxa_are_rows(datExpr_MB))), measures="Observed"))
rownames(dg_rich) <- "black"

rich_all_mod <- rbind(yel_rich,blue_rich,green_rich,orange_rich,dg_rich, black)

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/module_richness_time.pdf", height=4, width=4.5)
par(mar=c(3,4,1,4))
barplot(rich_all_mod, border = NA, axes = FALSE,col="white", cex.axis=0.8,cex.lab=0.8, space=c(0.5,2,2,1,3,3,0,2),cex=0.8, ylab="", xlab="", xaxt="n",ylim=c(0,125))
rect(-0.5, 120,2.5,-5,col = "gray85", density=NA)
rect(5.5, 120,8.5,-5,col = "gray85", density=NA)
rect(11.5, 120,14.5,-5,col = "gray85", density=NA)
rect(17.5, 120,20.5,-5,col = "gray85", density=NA)
par(new=TRUE)
env_MB <- read.csv("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/env_data/MBNMS_GHRSST_15_16.csv", header=TRUE)
#par(new=TRUE)
#plot(env_MB$Mean.SST~dmy(env_MB$Date),type="l",ylim=c(12,18), lwd=2,xlab="", ylab="",yaxt="n",xaxt="n",col=alpha("grey40"), lty=2)
#axis(side=4, cex.axis=0.8)
#mtext("Sea surface temperature",side=4,line=1.9,las=3, cex=0.8)
#par(new=TRUE)
barplot(rich_all_mod, col=color, cex.axis=0.8,cex.lab=0.8, space=c(0.5,2,2,1,3,3,0,2),cex=0.8, ylab="Number of taxa per subnetwork", xlab="", xaxt="n",ylim=c(0,125))
axis(side=1, at=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21),
 labels=c("Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec", "Jan", "Feb","Mar",
            "Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec"), las=3,cex.axis=0.7)
dev.off()

chooseTopHubInEachModule(datExpr_MB,moduleColors_MB, omitColors = "", power = 22,type = "unsigned")
GS1=as.numeric(cor(datTraits_MB$chlorophyll,datExpr_MB))
GeneSignificance=abs(GS1)

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/module_significance_chl.pdf", height=4, width=5)
plotModuleSignificance(GeneSignificance,moduleColors_MB,main="")
dev.off()

# Next module significance is defined as average gene significance.
ModuleSignificance=tapply(GeneSignificance, moduleColors_MB, mean, na.rm=T)

#STEP 5
modules = c("#00b159", "#ffc425", "#00aedb", "#f37735", "#8c8c8c","black")

# Select module probes
probes = names(as.data.frame(datExpr_MB))
inModule = is.finite(match(moduleColors_MB, modules));
modProbes = probes[inModule];

#modGenes = annot$gene_symbol[match(modProbes, annot$substanceBXH)];
# Select the corresponding Topological Overlap
TOM = TOMsimilarityFromExpr(datExpr_MB, power = 22,networkType="unsigned");
modTOM = TOM[inModule, inModule];
dimnames(modTOM) = list(modProbes, modProbes)

# Export the network into edge and node list files Cytoscape can read
cyt = exportNetworkToCytoscape(modTOM,
      edgeFile = paste("CytoscapeInput-edges-", paste(modules, collapse="-"), ".txt", sep=""),
      nodeFile = paste("CytoscapeInput-nodes-", paste(modules, collapse="-"), ".txt", sep=""),
      weighted = TRUE,threshold = 0.2, nodeNames = modProbes, nodeAttr = moduleColors_MB[inModule])

write.csv(cyt$edgeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_edge.csv")
write.csv(cyt$nodeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_node.csv")

#moduleColors_MB = gsub("yellow","#ffc425", gsub("blue","#00aedb", gsub("red", "#d11141", gsub("green","#00b159",gsub("brown","#f37735",gsub("turquoise","#8c8c8c",moduleColors_MB))))))

################ Choose only single module ###############
blue <- "#00aedb"

# Select module probes
inModule_blue = is.finite(match(moduleColors_MB, blue));
modProbes_blue = probes[inModule_blue];
TOM_blue = TOMsimilarityFromExpr(datExpr_MB, power = 22);
modTOM_blue = TOM_blue[inModule_blue, inModule_blue];
dimnames(modTOM_blue) = list(modProbes_blue, modProbes_blue)

cyt_blue = exportNetworkToCytoscape(modTOM_blue,
      edgeFile = paste("CytoscapeInput-edges-", paste(blue, collapse="-"), ".txt", sep=""),
      nodeFile = paste("CytoscapeInput-nodes-", paste(blue, collapse="-"), ".txt", sep=""),
      weighted = TRUE,threshold = 0.2, nodeNames = modProbes_blue, nodeAttr = moduleColors_MB[inModule_blue])

write.csv(cyt_blue$edgeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_edge_blue.csv")
write.csv(cyt_blue$nodeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_node_blue.csv")


dg <- "#8c8c8c"
# Select module probes
inModule_dg = is.finite(match(moduleColors_MB, dg));
modProbes_dg = probes[inModule_dg];
TOM_dg = TOMsimilarityFromExpr(datExpr_MB, power = 22);
modTOM_dg = TOM_dg[inModule_dg, inModule_dg];
dimnames(modTOM_dg) = list(modProbes_dg, modProbes_dg)

cyt_dg = exportNetworkToCytoscape(modTOM_dg,
      edgeFile = paste("CytoscapeInput-edges-", paste(blue, collapse="-"), ".txt", sep=""),
      nodeFile = paste("CytoscapeInput-nodes-", paste(blue, collapse="-"), ".txt", sep=""),
      weighted = TRUE,threshold = 0.2, nodeNames = modProbes_dg, nodeAttr = moduleColors_MB[inModule_dg])

write.csv(cyt_dg$edgeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_edge_dg.csv")
write.csv(cyt_dg$nodeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_node_dg.csv")

#export all modules separately
datExpr_MB <- as.data.frame(datExpr_MB)
grey_MB <- names(datExpr_MB)[moduleColors_MB=="black"] #grey
blue_MB <- names(datExpr_MB)[moduleColors_MB=="#00aedb"] #blue
dg_MB <- names(datExpr_MB)[moduleColors_MB=="#8c8c8c"] #dark grey
orange_MB <- names(datExpr_MB)[moduleColors_MB=="#f37735"] #orange
green_MB <- names(datExpr_MB)[moduleColors_MB=="#00b159"] #green
yel_MB <-names(datExpr_MB)[moduleColors_MB=="#ffc425"] #yellow
#red_MB <- names(datExpr_MB)[moduleColors_MB=="#d11141"] #red
write.csv(qpcR:::cbind.na(blue_MB,dg_MB,orange_MB,green_MB,yel_MB, grey_MB), file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/all_module_taxa.csv")

```

###SPLS analysis
```{r SPLS on dark grey and blue module,echo=FALSE,message=FALSE, warning=FALSE}
datExpr_MB <- as.data.frame(datExpr_MB)
datExpr_MB_t <- t(datExpr_MB)
blue_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="#00aedb"]) 
blue_MB$module <- "1"
names(blue_MB) <- c("taxa","module")
dg_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="#8c8c8c"])
dg_MB$module <- "2"
names(dg_MB) <- c("taxa","module")

blue_grey <- rbind(blue_MB,dg_MB)
blue_grey_taxa <- blue_grey[,1]
datExpr_MB_BG <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% blue_grey_taxa)
write.csv(datExpr_MB_BG, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/datExpr_MB_BG.csv")
trophic_lev <- read.csv(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/subnetxtrophic_ordered_20181112.csv")

blue_grey <- blue_grey[match(rownames(datExpr_MB_BG), blue_grey$taxa),]
blue_grey$trophic_level <- trophic_lev$trophic_fv[match(blue_grey$taxa, trophic_lev$taxa)]
blue_grey$Rank <- trophic_lev$Rank1[match(blue_grey$taxa, trophic_lev$taxa)]

datExpr_MB_BG <- t(datExpr_MB_BG)

head(cbind(rownames(datExpr_MB_BG), rownames(meta)))
pca.gene_BG <- pca(datExpr_MB_BG, ncomp = 8, center = TRUE, scale = TRUE)
plot(pca.gene_BG)
MB.pls_BG <- pls(datExpr_MB_BG, meta, ncomp = 6, mode = "regression")
MB.spls_BG <- spls(datExpr_MB_BG, meta, ncomp =6, mode = "regression")
tune.spls <- perf(MB.spls_BG, validation = 'Mfold',folds=8,
                  criterion = 'all', progressBar = FALSE, nrepeat=100)
plot(tune.spls$Q2.total)

summary(tune.spls$PRESS)
# to save as a pdf

#pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/SPLS_network.pdf", height=10, width=12)
#network(MB.spls_BG,color.node=c("grey", "white"),color.edge = c("red","orange","cyan","blue"),row.names=FALSE, cex.node.name=0.9,cutoff = 0.30)
#dev.off()

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/SPLS_heatmap_darkg_blue.pdf", height=6, width=9)
par(mar=c(1,1,1,1))
#RdYlBu <- t(brewer.pal(11,"RdYlBu"))
col_a <- colorRampPalette(c("#313695","#4575B4","#74ADD1","#ABD9E9","#E0F3F8","#FFFFBF","#FEE090","#FDAE61","#F46D43","#D73027","#A50026"))(90)
cim(MB.spls_BG, comp = 1:3, xlab = "",dist.method = c("euclidean", "euclidean"),color=col_a,row.sideColors = c("#00aedb", "#8c8c8c")[as.factor(blue_grey$module)],transpose=TRUE,threshold=0,keysize.label = 0.7,keysize =c(1, 1),row.cex=0.8,col.cex=0.6,ylab = "",margins = c(10, 8),row.names=FALSE,col.names=c("Upwelling","Temperature","Salinity","Chl. a","Nitrate","Diss. Oxygen"))
dev.off()
```

```{r SPLS for additional networks}
green_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="#00b159"]) 
green_MB$module <- "3"
names(green_MB) <- c("taxa","module")
#green_MB <- green_MB[,1]

yellow_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="#ffc425"])
yellow_MB$module <- "4"
names(yellow_MB) <- c("taxa","module")
#yellow_MB <- yellow_MB[,1]

orange_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="#f37735"]) 
orange_MB$module <- "5"
names(orange_MB) <- c("taxa","module")
#orange_MB <- orange_MB[,1]

black_MB <- data.frame(names(datExpr_MB)[moduleColors_MB=="black"]) 
black_MB$module <- "6"
names(black_MB) <- c("taxa","module")
#black_MB <- black_MB[,1]

gr_yel_ora_bl <- rbind(green_MB,yellow_MB,orange_MB,black_MB)
gr_yel_ora_bl_taxa <- gr_yel_ora_bl[,1]
gr_yel_ora_bl_MB <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% gr_yel_ora_bl_taxa)
gr_yel_ora_bl <- gr_yel_ora_bl[match(rownames(gr_yel_ora_bl_MB), gr_yel_ora_bl$taxa),]

gr_yel_ora_bl_MB <- t(gr_yel_ora_bl_MB)
MB.spls_gr_yel_ora_bl <- spls(gr_yel_ora_bl_MB, meta, ncomp = 6, mode = "regression")

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/SPLS_heatmap_gr_yel_ora_bla.pdf", height=6, width=9)
par(mar=c(1,1,1,1))
cim(MB.spls_gr_yel_ora_bl, comp = 1:3, xlab = "",dist.method = c("euclidean", "euclidean"),row.sideColors = c("#00b159", "#ffc425","#f37735","black")[as.factor(gr_yel_ora_bl$module)], color=col_a,transpose=TRUE,threshold=0,keysize.label = 0.7,keysize =c(1, 1),row.cex=0.8,col.cex=0.6,ylab = "",margins = c(10, 8),row.names=FALSE,col.names=c("Upwelling","Temperature","Salinity","Chl. a","Nitrate","Diss. Oxygen"))
dev.off()
```

```{r Random forest}
datExpr_MB_blue <- t(subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% blue_MB[,1]))
datExpr_MB_blue <- as.data.frame(datExpr_MB_blue)

library(randomForest) # load random forest package

rf_model = randomForest(datExpr_MB_blue[,1] ~ meta$upwelling + meta$temp + meta$salinity + meta$chlorophyll + meta$nitrate + meta$diss_oxygen) # train random forest model

plot(rf_model) # plot of error against number of trees grown
summary(rf_model)
```

####Line plots (a version of this will probably go into main document)
```{r nice line plots}
MB_merge_filt_t <- as.data.frame(t(MB_merge_filt))
write.csv(MB_merge_filt_t, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/merge_filt_t.csv")
MB_merge_filt_t$collection_date <- rownames(MB_merge_filt_t)

Otariidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Otariidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Otariidae")))
Carangidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Carangidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Carangidae")))
Syndiniaceae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Syndiniaceae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Syndiniaceae")))
Temoridae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Temoridae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Temoridae")))
#Metridinidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Metridinidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Metridinidae")))
Rhodospirillaceae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Rhodospirillaceae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Rhodospirillaceae")))

data_ggridges <- rbind(Otariidae,Carangidae,Temoridae,Syndiniaceae,Rhodospirillaceae)
data_ggridges$Date<-ymd(data_ggridges$Date)

data_ggridges <- dplyr::arrange(data_ggridges, Date)
DATES<-sort(data_ggridges$Date)
referenceTimePoint<-unique(DATES)[1] #set a reference time point at a particular sample
dayVector<-as.numeric(DATES-DATES[match(referenceTimePoint, DATES)]) #time difference in
data_ggridges <- cbind(data_ggridges,dayVector, DATES)
data_ggridges$Abundance <- data_ggridges$Abundance*500

library(ggplot2); library(ggridges); library(dplyr)
# Uncount copies the row "Abundance" number of times
Data_sum <- data_ggridges %>%
  tidyr::uncount(Abundance)
Data_sum$DATES <- ymd(Data_sum$DATES)

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/joyplot_dg.pdf",height=6,width=7)
ggplot(Data_sum, aes(x = dayVector, y = Taxa,fill=Taxa)) + 
  geom_density_ridges(scale=1.15, alpha=0.7, color="black",jittered_points = TRUE,
    position = position_points_jitter(width = 0.05, height = 0),
    point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7) +   
  scale_fill_manual(values = c("grey80", "grey60","grey80","grey60","grey80","grey60","grey80"), guide = "none") +
  theme_ridges(grid = FALSE, center = TRUE) +
  xlab("Days since April 30 2015") + ylab("")
dev.off()

#Code for trying to add points... 
# MB_all_filt_t <- as.data.frame(t(MB_all_filt))
# grey_points <- as.data.frame(cbind(MB_all_filt_t$`f:Otariidae`,MB_all_filt_t$`f:Carangidae`,
#                       MB_all_filt_t$`f:Temoridae`,MB_all_filt_t$`f:Syndiniaceae`,
#                       MB_all_filt_t$`f:Pelagibacteraceae`, MB_18S_fam@sam_data$collection_date))
# colnames(grey_points) <- c("Otariidae", "Carangidae","Temoridae","Syndiniaceae","Pelagibacteraceae", "Date")
# grey_points$Date<-dmy(grey_points$Date)
# grey_points <- dplyr::arrange(grey_points, Date)
# DATES_greypoints<-sort(grey_points$Date)
# referenceTimePoint_greypoints<-unique(DATES_greypoints)[1] #set a reference time point at a particular sample
# dayVector_grey<-as.numeric(DATES_greypoints-DATES_greypoints[match(referenceTimePoint_greypoints, DATES_greypoints)]) #time difference in
# grey_points <- cbind(grey_points,dayVector_grey, DATES_greypoints)
# #grey_points$Abundance <- grey_points$Abundance*100
# par(mfrow=c(3,1))
# par(mar=c(1,1,1,5))
# par(new=TRUE)
# plot(grey_points$dayVector_grey,grey_points$Temoridae, type="p", xaxt="n",yaxt="n", ylab="",xlab="",bty="n", pch=16, col="grey")


Balaenopteridae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Balaenopteridae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Balaenopteridae")))
Euphausiidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Euphausiidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Euphausiidae")))
#Corycaeidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Corycaeidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Corycaeidae")))
Bougainvilliidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Bougainvilliidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Bougainvilliidae")))
Puniceicoccaceae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Puniceicoccaceae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Puniceicoccaceae")))
Urechidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Urechidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Urechidae")))
Sugiuridae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Sugiuridae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Sugiuridae")))
#Calanidae <- cbind(data.frame(Abundance=MB_merge_filt_t$`f:Calanidae`),data.frame(Date=MB_merge_filt_t$collection_date), Taxa=(c("Calanidae")))


data_ggridges_b <- rbind(Balaenopteridae,Euphausiidae,Urechidae,Sugiuridae,Puniceicoccaceae)
data_ggridges_b$Date<-ymd(data_ggridges_b$Date)

data_ggridges_b <- dplyr::arrange(data_ggridges_b, Date)
DATES<-sort(data_ggridges_b$Date)
referenceTimePoint<-unique(DATES)[1] #set a reference time point at a particular sample
dayVector<-as.numeric(DATES-DATES[match(referenceTimePoint, DATES)]) #time difference in
data_ggridges_b <- cbind(data_ggridges_b,dayVector, DATES)
data_ggridges_b$Abundance <- data_ggridges_b$Abundance*1000

library(ggplot2); library(ggridges); library(dplyr)
# Uncount copies the row "Abundance" number of times
Data_sum_b <- data_ggridges_b %>%
  tidyr::uncount(Abundance)
Data_sum_b$DATES <- ymd(Data_sum_b$DATES)

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/joyplot_blue.pdf",height=6,width=7)
ggplot(Data_sum_b, aes(x = dayVector, y = Taxa,fill=Taxa)) + 
  geom_density_ridges(scale=1.15, alpha=0.6,color="black",jittered_points = TRUE,
    position = position_points_jitter(width = 0.05, height = 0),
    point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7) +   
  scale_fill_manual(values = c("#00aedb", "lightblue1","#00aedb","lightblue1","#00aedb","lightblue1"), guide = "none") + theme_ridges(grid = FALSE, center = TRUE)+
  xlab("Days since April 30 2015") + ylab("")
dev.off()
```

```{r pie charts of trophic levels}
trophic_blue <- c(9, 27, 8, 36, 1)
trophic_blue <- prop.table(trophic_blue)*100
labels_blue <- c("Saprotrophs (11.0%)", "Autotrophs (33.3%)", "Primary consumers (9.8%)", "Secondary consumers (44.4%)","Tertiary consumers (1.2%)")

trophic_grey <- c(26, 20, 12, 55, 1)
trophic_grey <- prop.table(trophic_grey)*100
labels_grey <- c("Saprotrophs (22.8%)", "Autotrophs (17.5%)", "Primary consumers (10.5%)", "Secondary consumers (48.2%)","Tertiary consumers (0.9%)")

# Plot the chart.
pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/trophic_pie_blue.pdf", height=5, width=7)
pie(trophic_blue,labels_blue, border=FALSE,col=c("lightcyan","lightblue","#00aedb","#2b8cbe","steelblue4"), cex=0.8)
dev.off()
pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/trophic_pie_grey.pdf", height=5, width=7)
pie(trophic_grey,labels_grey, border=FALSE,col=c("grey95","grey80","grey60","grey40","grey20"),cex=0.8)
dev.off()

```

```{r intramodular connectivity}
con <- intramodularConnectivity.fromExpr(datExpr_MB, moduleColors_MB, 
              corFnc = "cor", corOptions = "use = 'p'",
              weights = NULL,
              distFnc = "dist", distOptions = "method = 'euclidean'",
              networkType = "signed", power = 22,
              scaleByMax = FALSE,
              ignoreColors = if (is.numeric(colors)) 0 else "grey",
              getWholeNetworkConnectivity = TRUE)

con$taxa <- rownames(t(datExpr_MB))
blue_MB <- blue_MB[,1]
con_blue <- con[con$taxa %in% blue_MB, ]
write.csv(con_blue, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_blue.csv")
trophic <- read.csv(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/subnetxtrophic_ordered_20181112.csv")
trophic_lev <- read.csv(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/subnetxtrophic_ordered_20181112.csv")
con_blue$trophic_lev <- trophic_lev$trophic_fv[match(con_blue$taxa, trophic_lev$taxa)]
dg_MB <- dg_MB[,1]
con_dg <- con[con$taxa %in% dg_MB, ]
write.csv(con_dg, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_dg.csv")
con_dg$trophic_lev <- trophic_lev$trophic_fv[match(con_dg$taxa, trophic_lev$taxa)]

#Blue and grey separately!
datExpr_MB_Blue <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% blue_MB)
datExpr_MB_grey <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% dg_MB)
cor_blue <- cor(as.matrix(t(datExpr_MB_Blue)),meta, method = "pearson")
cor_blue <- as.data.frame(cor_blue)
cor_dg <- cor(as.matrix(t(datExpr_MB_grey)),meta, method = "pearson")
cor_dg <- as.data.frame(cor_dg)

pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/con_env.pdf", height=5, width=9)
par(mfrow=c(1,2))
par(mar=c(4,4,3,2.7))
df_blue <- data.frame(cor_blue$temp,con_blue$kWithin,con_blue$trophic_lev)
plot(df_blue$cor_blue.temp,df_blue$con_blue.kWithin,cex.axis=0.8,pch=c(15,23,16,17,25)[as.factor(df_blue$con_blue.trophic_lev)],ylim=c(-1.0,18), col="#00aedb",bg="#00aedb",ylab="Intra-network connectivity",xlab="Correlation w/ Temperature")
#lm_blue <- lm(con_blue.kWithin~cor_blue.temp, data=df_blue)
lm_blue <- nls(con_blue.kWithin ~ exp(a + b * cor_blue.temp), data = df_blue, start = list(a = 0, b = 0))
#summary(lm_blue)
newblue <- seq(min(df_blue$cor_blue.temp), max(df_blue$cor_blue.temp), 0.001)
pre_blue <- predict(lm_blue, newdata=data.frame(cor_blue.temp=newblue), interval="confidence")
lines(newblue,pre_blue, lty=2,col="grey50")
#newblue <- seq(min(df_blue$cor_blue.temp), max(df_blue$cor_blue.temp), 0.001)
#pre_blue <- predict(lm_blue, newdata=data.frame(cor_blue.temp=newblue), interval="confidence")
#lines(newblue, pre_blue[,2], lty=2,col="grey50")
#lines(newblue, pre_blue[,3], lty=2, col="grey50")
#abline(v=0.4, lwd=2, col="orangered", lty=2)
abline(h=15, lwd=2,col="orangered", lty=2)
#legend("topright", legend=substitute(paste(r, " = ", r2,", p<0.001"), list(r2 = round(summary(lm_blue)$adj.r.squared, digits=2))),cex=0.9,bty="n")
#legend("toplef", legend="B", bty="n", cex=0.9)

par(mar=c(4,2.7,3,4))
df_dg <- data.frame(cor_dg$chlorophyll,con_dg$kWithin, con_dg$trophic_lev)
plot(df_dg$cor_dg.chlorophyll,df_dg$con_dg.kWithin,bg="#8c8c8c",pch=c(15,23,16,17,25)[as.factor(df_dg$con_dg.trophic_lev)],ylim=c(0.5,35),cex.axis=0.8,ylab="",col="#8c8c8c", xlab="Correlation w/ Chlorophyll a")
lm_dg <- nls(con_dg.kWithin ~ exp(a + b * cor_dg.chlorophyll), data = df_dg, start = list(a = 0, b = 0))
summary(lm_dg)
newdg <- seq(min(df_dg$cor_dg.chlorophyll), max(df_dg$cor_dg.chlorophyll), 0.001)
pre_dg <- predict(lm_dg, newdata=data.frame(cor_dg.chlorophyll=newdg), interval="confidence")
lines(newdg,pre_dg, lty=2,col="grey50")
#lm_dg <- lm(con_dg.kWithin~cor_dg.chlorophyll, data=df_dg)
#newdg <- seq(min(df_dg$cor_dg.chlorophyll), max(df_dg$cor_dg.chlorophyll), 0.001)
#pre_dg <- predict(lm_dg, newdata=data.frame(cor_dg.chlorophyll=newdg), interval="confidence")
#lines(newdg, pre_dg[,1], lty=1,col="grey50")
#lines(newdg, pre_dg[,2], lty=2,col="grey50")
#lines(newdg, pre_dg[,3], lty=2, col="grey50")
#abline(v=-0.4, lwd=2, col="orangered", lty=2)
abline(h=32.5, lwd=2,col="orangered", lty=2)
#legend("topright",legend=substitute(paste(r, " = ", r2,", p<0.001"), list(r2 = round(summary(lm_dg)$adj.r.squared, digits=2))), cex=0.9, bty="n")
#legend("toplef", legend="C", bty="n", cex=0.9)
dev.off()

```

```{r re-export networks with connectedness and trophic level}
cyt_blue$nodeData$trophic_level <- trophic_lev$trophic_fv[match(cyt_blue$nodeData$nodeName, trophic_lev$taxa)]
cyt_blue$nodeData$connectivity <- con_blue$kWithin[match(cyt_blue$nodeData$nodeName, con_blue$taxa)]

write.csv(cyt_blue$edgeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_edge_blue.csv")
write.csv(cyt_blue$nodeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_node_blue.csv")

cyt_dg$nodeData$trophic_level <- trophic_lev$trophic_fv[match(cyt_dg$nodeData$nodeName, trophic_lev$taxa)]
cyt_dg$nodeData$connectivity <- con_dg$kWithin[match(cyt_dg$nodeData$nodeName, con_dg$taxa)]

write.csv(cyt_dg$edgeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_edge_dg.csv")
write.csv(cyt_dg$nodeData, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/MB_node_dg.csv")

```

###PCA
```{r env traits based on PCA,echo=FALSE,message=FALSE, warning=FALSE}
#meta<-read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/m2w_metadata_MB.csv")
#names(meta)
#DATES<-str_split(meta$SAMPLING_date_time, " ", simplify=T)[,2]
meta2<-meta[,c(1,2,3,4,5)]
standard<-decostand(meta2, method="max") #standardize variables

	#PCA
envir.PCA <- prcomp(standard, scale=TRUE)
#?prcomp
#summary(envir.PCA)
Loadings <- as.data.frame(envir.PCA$rotation[,1:5])
scores <- as.data.frame(envir.PCA$x[,1:5])
fviz_eig(envir.PCA)
#fviz_pca_ind(envir.PCA)
  
#plotting w ggfortify; see https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html
#pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/envirPCA.pdf")
autoplot(envir.PCA,
         loadings = T, loadings.label = T, loadings.label.size = 4)+
  theme_minimal()
  #annotate("text", x = -0.2, y=0.28, label = "Upwelling", color = "red")+
  #annotate("text", x = 0.25, y=0.21, label = "Nitrate", color = "red")+
  #annotate("text", x = -0.05, y= -0.07, label = "Temperature", color = "red")+
  #annotate("text", x = 0.032, y= -0.01, label = "Salinity", color = "red")+
  #annotate("text", x = -0.06, y= -0.01, label = "Oxygen", color = "red")
#dev.off()
	
moduleTraitCor_MB = cor(MEs_MB, meta2, use = "p");
moduleTraitPvalue_MB = corPvalueStudent(moduleTraitCor_MB, nSamples_MB);

# Will display correlations and their p-values
textMatrix_MB =  paste(signif(moduleTraitCor_MB, 2), "\n(",
                    signif(moduleTraitPvalue_MB, 1), ")", sep = "");

labeledHeatmap(Matrix = moduleTraitCor_MB,
              xLabels = names(scores),
              yLabels = names(MEs_MB),
              yColorLabels = TRUE,
              ySymbols = names(MEs_MB),
              colorLabels = FALSE,
              colors = blueWhiteRed(50),
              textMatrix = textMatrix_MB,
              setStdMargins = FALSE,
              cex.text = 0.5,
              naColor = "grey",
              zlim = c(-1,1),
              main = paste("Module-trait relationships"))

############### BIOENV #######
MB_all_tax_df <- t(data.frame(MB_all_tax_ps_rel@otu_table))
meta_bioenv<-read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/m2w_metadata_MB.csv")
meta_bioenv<-meta_bioenv[,c(18,47,48,49,51,52)]
bioenv <- bioenv(MB_all_tax_df, meta_bioenv, method="kendall", index="bray")

capscale <- capscale(MB_all_tax_df ~ upwelling+temp+salinity+chlorophyll+nitrate+diss_oxygen, meta_bioenv, distance = "bray")

#summary(capscale)
plot(capscale, main="capscale")
#anova(capscale, by='margin')

```

###Pseudoautocorrelation of modules
```{r pseudo autocorrelation of all module MB,echo=FALSE,message=FALSE, warning=FALSE}
#filter out desired color module
MB_taxa_yel = prune_taxa(yel_MB, MB_all_filt)
yel_otu_MB<-otu_table(MB_taxa_yel)
dates_MB<-dmy(sample_data(MB_all_tax_ps_rel)$collection_date)

#MB_taxa_red = prune_taxa(red_MB,MB_all_filt)
#red_otu_MB<-otu_table(MB_taxa_red)

MB_taxa_blue = prune_taxa(blue_MB,MB_all_filt)
blue_otu_MB<-otu_table(MB_taxa_blue)

MB_taxa_green = prune_taxa(green_MB,MB_all_filt)
green_otu_MB<-otu_table(MB_taxa_green)

MB_taxa_dg = prune_taxa(dg_MB,MB_all_filt)
dg_otu_MB<-otu_table(MB_taxa_dg)

#dist.yel_sa_MB <- OneStep(OTUs=yel_otu_MB, DATES=dates_MB, METHOD="jaccard")
#dist.red_sa_MB <- OneStep(OTUs=red_otu_MB, DATES=dates_MB, METHOD="jaccard")
dist.blue_sa_MB <- OneStep(OTUs=blue_otu_MB, DATES=dates_MB, METHOD="bray")
#dist.green_sa_MB <- OneStep(OTUs=green_otu_MB, DATES=dates_MB, METHOD="jaccard")
dist.dg_sa_MB <- OneStep(OTUs=dg_otu_MB, DATES=dates_MB, METHOD="bray")

bray_ref_b <- vegdist(t(blue_otu_MB[,1:3]), method="bray")
mean(bray_ref_b)

bray_ref_g <- vegdist(t(dg_otu_MB[,1:3]),method="bray")
mean(bray_ref_g)

colMeans(dist.blue_sa_MB)
colMeans(dist.dg_sa_MB)

#PLOT DARK GREY AND BLUE
pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/blue_dg_PA.pdf",height=6,width=6)
par(mfcol=c(2,1))
par(mar=c(0.5,5,3,4))
boxplot(dist.dg_sa_MB, cex.lab=0.8,cex.axis=0.6,las=1,xlab="", at=c(1,4.5,7.5,12.5,18,19,22),ylab="Jaccard Distance", xlim=c(-1.8,22), cex=0.8,ylim=c(0.45,1), col="#8c8c8c",xaxt="n")
#axis(side=1, at=c(1,3.5,7.5,12.5,18,19,22),
#     labels=c("July","Sep", "Dec","Apr", "Aug","Sep", "Dec"), las=3,cex.axis=0.7)
legend("topleft", "A", bty="n")
#axis(side=1, at=c(1,2,3,4,5,6,7), labels=c("0","68","133","229","357","489","515"),las=1,cex.axis=1)
par(new=TRUE)
plot(env_MB_high_res$chl_gff~dmy(env_MB_high_res$date),type="l",ylim=c(-1,20), lwd=5,xlab="", ylab="",yaxt="n",xaxt="n",col=alpha("grey",0.5))
axis(side=4, cex.axis=0.7, las=1)
mtext("Chlorophyll a",side=4,line=1.9,las=3, cex=0.8)
par(mar=c(3,5,0.5,4))
boxplot(dist.blue_sa_MB,cex.lab=0.8, cex.axis=0.6,las=1,xlab="", at=c(1,4.5,7.5,12.5,18,19,22),ylab="Jaccard Distance", xlim=c(-1.8,22), ylim=c(0.45,1), col="#00aedb",xaxt="n")
axis(side=1, at=c(-2,1,4.5,7.5,12.5,18,19,22),
     labels=c("Apr","July","Oct", "Dec","Apr", "Aug","Sep", "Dec"), las=3,cex.axis=0.7)
par(new=TRUE)
env_MB <- read.csv("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/env_data/MBNMS_GHRSST_15_16.csv", header=TRUE)
plot(env_MB$Mean.SST~dmy(env_MB$Date),type="l",ylim=c(12,20), lwd=5,xlab="", ylab="",yaxt="n",xaxt="n",col=alpha("grey",0.5))
legend("topleft", "B", bty="n")
axis(side=4, las=1, cex.axis=0.6)
mtext("Sea surface temp.",cex=0.8,side=4,line=1.9,las=3)
dev.off()


pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/blue_dg_PA_env.pdf",height=6,width=6)
dif_SA<-read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/dif_SA.csv")
par(mfrow=c(2,1))
par(mar=c(4,4,1,1))
plot(dif_SA$dif_SST,dif_SA$dif_blue, xlab="Delta T",log="",ylab="Delta Jaccard", col="#00aedb", pch=19)
plot(dif_SA$dif_chl,dif_SA$dif_grey, xlab="Delta Chl.",log="",ylab="Delta Jaccard", col="grey",pch=19)
dev.off()

```

```{r average line plots by module}
par(mfrow=c(3,2))
MB_taxa_yel = prune_taxa(yel_MB,MB_merge_filt)
yel_otu_MB<-otu_table(MB_taxa_yel)
ave_yel_otu_MB <- colMeans(yel_otu_MB)
plot(ave_yel_otu_MB~ dmy(traitData_MB$collection_date),lwd=2.5, type="l", col="#ffc425",ylab="Relative abundance")

MB_taxa_blue = prune_taxa(blue_MB,MB_merge_filt)
blue_otu_MB<-otu_table(MB_taxa_blue)
ave_blue_otu_MB <- colMeans(blue_otu_MB)
plot(ave_blue_otu_MB~ dmy(traitData_MB$collection_date),lwd=2.5,col="#00aedb", type="l",ylab="Relative abundance")

MB_taxa_green = prune_taxa(green_MB,MB_merge_filt)
green_otu_MB<-otu_table(MB_taxa_green)
ave_green_otu_MB <- colMeans(green_otu_MB)
plot(ave_green_otu_MB~ dmy(traitData_MB$collection_date),lwd=2.5, col="#00b159",type="l",ylab="Relative abundance")

MB_taxa_dg = prune_taxa(dg_MB,MB_merge_filt)
dg_otu_MB<-otu_table(MB_taxa_dg)
ave_dg_otu_MB <- colMeans(dg_otu_MB)
plot(ave_dg_otu_MB~ dmy(traitData_MB$collection_date), type="l",lwd=2.5,col="#8c8c8c",ylab="Relative abundance")

MB_taxa_orange = prune_taxa(orange_MB,MB_merge_filt)
orange_otu_MB<-otu_table(MB_taxa_orange)
ave_orange_otu_MB <- colMeans(orange_otu_MB)
plot(ave_orange_otu_MB~ dmy(traitData_MB$collection_date), type="l",lwd=2.5,col="#f37735",ylab="Relative abundance")

MB_taxa_black = prune_taxa(grey_MB,MB_merge_filt)
black_otu_MB<-otu_table(MB_taxa_black)
ave_black_otu_MB <- colMeans(black_otu_MB)
plot(ave_black_otu_MB~ dmy(traitData_MB$collection_date), type="l",lwd=2.5,col="black",ylab="Relative abundance")


### plot by centric, pennate, and dinoflagellates
diatoms <- read.csv(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/subnettroph_AD.csv")

centric = subset(diatoms, group_added == "centric_diatom")
centric <- prune_taxa(centric$taxa,MB_merge_filt)
centric_ave <- colMeans(centric)

pennate = subset(diatoms, group_added == "pennate_diatom")
pennate <- prune_taxa(pennate$taxa,MB_merge_filt)
pennate_ave <- colMeans(pennate)

dinos = subset(diatoms, group_added == "dinoflagellates")
dinos <- prune_taxa(dinos$taxa,MB_merge_filt)
dinos_ave <- colMeans(dinos)

copepod = subset(diatoms, group_added == "copepod")
copepod <- prune_taxa(copepod$taxa,MB_merge_filt)
copepod_ave <- colMeans(copepod)


pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/diatom_dino.pdf",height=5,width=6)
par(mar=c(6,4,3,3))
plot(env_MB$Mean.SST~dmy(env_MB$Date),type="n",ylim=c(10,19), lwd=5,xlab="", ylab="",yaxt="n",xaxt="n",col=alpha("grey",0.5))
subdate <- c(ydm("2013-20-01"),dmy(env_MB$Date),ydm("2020-31-01"))
sub.sst <- c(0,env_MB$Mean.SST,0)
axis(side=4)
mtext("Sea surface temperature",side=4,line=1.9,las=3)
polygon(subdate, sub.sst, col='gray90', border=NA, density=30) 
par(new=TRUE)
#all <- prop.table(rbind(centric_ave,pennate_ave,dinos_ave,copepod_ave), margin=2)
#barplot(all, col=c("#a8ddb5","#2ca25f","#feb24c","grey40"), las=2)
plot(centric_ave~ dmy(traitData_MB$collection_date),ylim=c(0,0.8), type="l",lwd=2.5,col="#a8ddb5",ylab="Relative abundance", xaxt="n", xlab="")
axis.Date(1,at=dmy(traitData_MB$collection_date),labels=format(dmy(traitData_MB$collection_date),"%b-%d"),las=2)
lines(pennate_ave~ dmy(traitData_MB$collection_date), col="#2ca25f",lwd=2.5)
lines(dinos_ave~ dmy(traitData_MB$collection_date), col="#feb24c",lwd=2.5)
lines(copepod_ave~ dmy(traitData_MB$collection_date), col="grey40",lwd=2.5)
legend("topright",legend=c("Centric diatoms", "Pennate diatoms","Dinoflagellates","Copepods"),ncol=2,col=c("#a1d99b","#2ca25f","#feb24c","black"), bty="n", lty=c(1,1,1,1), cex=0.7)
dev.off()

centric_rich <- specnumber(t(centric))
pennate_rich <- specnumber(t(pennate))
dino_rich <- specnumber(t(dinos))
copepod_rich <- specnumber(t(copepod))
phyto_rich <- rbind(centric_rich,pennate_rich,dino_rich,copepod_rich)
barplot(prop.table(phyto_rich, margin=2), las=2, col=c("#a8ddb5","#2ca25f","#feb24c","grey40"))

```

```{r lag analysis, eval=FALSE, include=FALSE}
#LAGGED CORRELATION Matrix
source("/Volumes/GoogleDrive/Team Drives/m2w_analysis/analysis/LagAnalysis.R")
lagMB <- LAGCOR(otus, lag = 1)
    #reshape
    lagMB <- melt(lagMB)%>%
      filter(!is.na(value))%>%
      filter(value > 0.62)%>%
      arrange(desc(value))
        lagMB[,1] <- rownames(otus)[lagMB[,1]]
        lagMB[,2] <- rownames(otus)[lagMB[,2]]
        names(lagMB) <- c("Lagging", "Leading", "Kendall")
        
    head(lagMB)
    length(unique(lagMB$Lagging))

    #save(lagMB, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/analysis/LaggedKendall.Rdata")
        
    #especially interesting leading/lagging correlations might be taxa that appear in at least 3-4 time points...
    #and with very high correlation coefficients
    lagMB[lagMB$Lagging %in% row.names(otus)[specnumber(otus)>3] &
      lagMB$Kendall > 0.85,]
  
```

####Richness and Pseudoautocorrelation of whole community
```{r Richness of total taxa, echo=FALSE, fig.cap="\\label{fig:fig S1}Figure S1: A: Total richness (number of taxa) in Monterey Bay National Marine Sanctuary through April 2015 - December 2016 with sea surface temperature anomaly. B: Pseudo-autocorrelation analyses across all taxa compared to the time point prior to it. First time point is zero due to not having a reference point. The vertical dashed line represents December 31, 2015.", fig.height=8, fig.width=6.5}
pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/Supplemental/obs_richness_PA.pdf",height=6,width=9)
par(mar=c(3,4,2,4.5))
par(mfrow=c(1,2))
otu_table(MB_all_filt) <- otu_table(round(as((otu_table(MB_all_filt)), "matrix")), taxa_are_rows(MB_all_filt)) #doesn't work to 
richness_total_MB <- setNames(cbind(estimate_richness(MB_all_filt, measures="Observed"),MB_all_tax_ps_rel@sam_data$collection_date, MB_all_tax_ps_rel@sam_data$locus),c("richness","YEAR_DATE", "locus"))
boxplot(richness_total_MB$richness~ymd(richness_total_MB$YEAR_DATE),
        main="", at=c(1,4,7,9,13,17,18,21), cex.axis = 0.8,xlim=c(0,21), las=2, ylim=c(0,100),
       xaxt="n",col="grey90",ylab=c("Number of taxa"))
abline(v=c(10), col=c("black"), lty=c(2), lwd=c(1))
axis(side=1, at=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21),
 labels=c("Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec", "Jan", "Feb","Mar",
            "Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec"), las=3,cex.axis=0.7)
mtext("2015", side=1, line=3, at=4,cex=0.8)
mtext("2016", side=1, line=3, at=16,cex=0.8)
env_MB <- read.csv("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/env_data/MBNMS_GHRSST_15_16.csv", header=TRUE)
par(new=TRUE)
plot(env_MB$Mean.SST~dmy(env_MB$Date),type="l",ylim=c(10,20), lwd=5,xlab="", ylab="",yaxt="n",xaxt="n",col=alpha("grey",0.5))
axis(side=4)
mtext("Sea surface temperature",side=4,line=1.9,las=3)
legend("topleft", "A", bty="n")
#dev.off()

#PA
OTUs_MB<-otu_table(MB_all_tax_ps_ts)
dates_MB<-ymd(sample_data(MB_all_tax_ps_ts)$collection_date)
dist.res_MB_sa <- OneStep(OTUs=OTUs_MB, DATES=dates_MB, METHOD="jaccard")
#plot object in base R
par(mar=c(3,4.5,2,4))
boxplot(dist.res_MB_sa, at=c(4,7,9,13,17,18,21),xlim=c(0,21),xlab="", ylab="Euclidian Distance", xlim=c(0,21.5), ylim=c(0.7,0.9), col="grey90",xaxt="n")
abline(v=c(10), col=c("black"), lty=c(2), lwd=c(1))
axis(side=1, at=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21),
     labels=c("Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec", "Jan", "Feb","Mar",
              "Apr", "May", "June", "July", "Aug","Sep", "Oct", "Nov", "Dec"), las=3,cex.axis=0.7)
mtext("2015", side=1, line=3, at=4,cex=0.8)
mtext("2016", side=1, line=3, at=16,cex=0.8)
legend("topleft", "B", bty="n")
dev.off()


```

####Heatmap and dendrogram of top taxa
```{r heatmap of top taxa, echo=FALSE, fig.cap="\\label{fig:fig S2}Figure S2: Dendrogram of the top 100 taxa for FK left and MB right. Dissimilarity between taxa was calculated based on a Euclidean distance matrix.", fig.height=8, fig.width=10, message=FALSE, warning=FALSE}
#pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/Supplemental/heatmap.pdf",height=10,width=7)
top_50_MB <- prune_taxa(names(sort(taxa_sums(MB_merge_filt),
         TRUE)[1:100]),MB_merge_filt)

#pushViewport(viewport(x = 0))
draw(Heatmap(data.frame(top_50_MB@.Data),row_names_gp = gpar(fontsize = 8),col=pal,column_title_gp = gpar(fontsize = 8),clustering_distance_rows = "euclidean",column_dend_height = unit(6, "mm"),column_names_gp = gpar(fontsize = 8),row_title_gp=gpar(fontsize=8),km_title = "cluster% i", name = "MB"),k=4, newpage = FALSE)
#popViewport()
#dev.off()
```

```{r boxplot of connections and trophic level}
boxplot(con_blue$kWithin~con_blue$trophic_lev)
boxplot(con_dg$kWithin~con_dg$trophic_lev)
```

```{r line plots, echo=FALSE, fig.cap="\\label{fig:fig 3}Figure 3: Some of the co-occuring organisms with the highest correlations from FKNMS (left) and MBNS (right).", fig.height=5.5, fig.width=5.5, message=FALSE, warning=FALSE}
par(mfcol=c(2,1))
par(mar=c(1,4,3,2))
#MB
plot(MB_merge_filt_t$`f:Noelaerhabdaceae`~MB_merge_filt_t$collection_date,col="#E69F00",type="l", pch=16,lwd=2,ylab=c(""), xlab="",xaxt="n",yaxt="n",ylim=c(0,1.2))
#lines(MB_all_merge$`f:Pelagibacteraceae`~MB_all_merge$collection_date, col="gold", pch=16, lwd=2)
lines(MB_merge_filt_t$`f:Engraulidae`~MB_merge_filt_t$collection_date,lwd=2, col="darkorange3")
lines(MB_merge_filt_t$`f:Balaenopteridae`~MB_merge_filt_t$collection_date,lwd=2, 
col="black")
#lines(MB_all_merge$f.Calanidae/max(MB_all_merge$f.Calanidae)~MB_all_merge$collection_date,lwd=2, col="grey")
legend("topleft",legend=c("Noelaerhab.", "Engraulidae","Balaenoptera"),ncol=2,col=c("darkorange3","#E69F00","black"), bty="n", lty=c(1,1,1), cex=0.6)
abline(v=c(16805), col=c("black"), lty=c(2), lwd=c(1))
par(mar=c(4,4,0,2))
plot(MB_merge_filt_t$`f:Paracalanidae`~MB_merge_filt_t$collection_date, col="darkolivegreen3", pch=16, lwd=2,xlab="", xaxt="n",ylab=c(""),yaxt="n",ylim=c(0,1.2),type="l")
lines(MB_merge_filt_t$`f:Thalassiosiraceae`~MB_merge_filt_t$collection_date, col="#009E73", pch=16, lwd=2)
lines(MB_merge_filt_t$`f:Chaetocerotaceae`~MB_merge_filt_t$collection_date, col="darkolivegreen", pch=16, lwd=2)
lines(MB_merge_filt_t$`f:Clupeidae`~MB_merge_filt_t$collection_date,lwd=2, col="grey")
axis(1, ymd(MB_merge_filt_t$collection_date), format(ymd(MB_merge_filt_t$collection_date), "%b"), cex.axis = .7, las=3)
legend("topleft",legend=c("Paracalanidae", "Thalassiosir.","Chaetoceros", "Clupeidae"),col=c("darkolivegreen3","#009E73","darkolivegreen", "grey"), bty="n", ncol=2,lty=c(1,1,1), cex=0.6)
abline(v=c(16805), col=c("black"), lty=c(2), lwd=c(1))
mtext("2015", side=1, line=3, at=15650,cex=0.7)
mtext("2016", side=1, line=3, at=19000,cex=0.7)

#dev.off()
#cor(MB_all_merge$f.Paracalanidae,MB_all_merge$f.Calanidae)

```

####Correlation matrix of top taxa
```{r plots of correlations, echo=FALSE, fig.cap="\\label{fig:fig S4}Figure S4: Correlation of the top 50 taxa for Monterey Bay only including significant values of a p-value equal to or less than 0.05. These correlation matrices were performed on relative abundance indices and ordered by hierarcical clustering on dissimilarities between taxa", fig.height=8, fig.width=7, message=FALSE, warning=FALSE}
#MB
#pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/Supplemental/correlation_top50.pdf",height=8,width=7)
top_taxa_merge_MB <- prune_taxa(names(sort(taxa_sums(MB_all_tax_ps_ts_merge),
         TRUE)[1:50]),MB_all_tax_ps_ts_merge) #use transformed merged data
cor_MB <- as.matrix(top_taxa_merge_MB@otu_table)
#res2_MB<-rcorr(cor_MB,type="spearman")
res2_MB <- cor(cor_MB, method="kendall")
#saveRDS(res2_MB, "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/taxa_cor_MB.Rdata")  
corrplot(res2_MB, type="lower", order="hclust", 
          sig.level = 0.05, tl.srt=45,tl.col="black", insig = "blank",tl.cex=0.6,diag=FALSE)
#dev.off()
```

```{r Ordinations, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
MB_all_tax_df <- t(data.frame(MB_all_tax_ps_rel@otu_table))
meta_bioenv<-read.csv("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/m2w_metadata_MB.csv")
meta_bioenv<-meta_bioenv[,c(18,47,48,49,51,52)]
bioenv <- bioenv(MB_all_tax_df, meta_bioenv)
summary(bioenv)

vegdist_MB <- vegdist(MB_all_tax_df, method="jaccard") # Bray-Curtis distances between the rows
metaMDS_MB <- metaMDS(vegdist_MB,verbose = FALSE) # k is the number of dim
#metaMDS_MB # view results
# plot solution 
x_MB <- metaMDS_MB$points[,1]
y_MB <- metaMDS_MB$points[,2]

FK_all_tax_df <- t(data.frame(FK_all_tax_ps_rel@otu_table))
vegdist_FK <- vegdist(FK_all_tax_df, method="jaccard") # Bray-Curtis distances between the rows
metaMDS_FK <- metaMDS(vegdist_FK,verbose = FALSE) # k is the number of dim
# plot solution phytoplankton
x_FK <- metaMDS_FK$points[,1]
y_FK <- metaMDS_FK$points[,2]

all_data <- merge_phyloseq(MB_all_tax_ps_ts,FK_all_tax_ps_ts)
all_Data.ord <- ordinate(all_data, "NMDS", "jaccard")
```

```{r plot ordinations, eval=FALSE, fig.cap="\\label{fig:fig 5}Figure 5: Canonical correspondence analysis of both locations FK (left) and MB (right). The points are colored by replicate with point type representing year (2015=square, 2016=circle). The text is sample collection date. Distance matrix is jaccard.", fig.height=4, fig.width=6, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow=c(1,2))
par(mar=c(4,5,2,0))
sam_FK_df <- data.frame(FK_all_tax_ps_rel@sam_data)
plot(x_FK, y_FK,xlab="Coordinate 1", main="", ylab="Coordinate 2",col=c(cbbPalette[FK_all_tax_ps_rel@sam_data$collection_date]),pch=c(15,19)[as.factor(FK_all_tax_ps_rel@sam_data$year)])
text(x_FK, y_FK,label=FK_all_tax_ps_rel@sam_data$collection_date,cex=0.5)
expl_FK <- subset(sam_FK_df, select=c("TMP_C","CHL_MG_M.3","NO3_um"))
plot(envfit(metaMDS_FK, expl_FK),col="black", cex=0.5)
legend("topleft", "A", bty="n")

par(mar=c(4,1,2,4))
plot(x_MB, y_MB, xlab="Coordinate 1", main="", yaxt="n",ylab="Coordinate 2",col=c(cbbPalette[MB_18S_fam@sam_data$collection_date]),pch=c(15,19)[as.factor(MB_18S_fam@sam_data$year)])
text(x_MB, y_MB,label=MB_18S_fam@sam_data$collection_date,cex=0.5)
sam_MB_df <- data.frame(MB_18S_fam@sam_data)
expl_MB <- subset(sam_MB_df, select=c("temp","nitrate","salinity","chlorophyll"))
plot(envfit(metaMDS_MB, expl_MB),col="black",cex=0.5)
legend("topleft", "B", bty="n")
```
####Finding Kendall threshold for taxa filtering
```{r Finding Kendall threshold for merged otu table, echo=FALSE, message=FALSE, warning=FALSE}
#One can imagine different permutation procedures; here are two.

  #function to scramble an existing dataset
  PERMFUN <- function(z) {matrix(sample(z),nrow=nrow(z))}
  propObs <- function(data, x) {sum(abs(data) >= x) / length(data)}  #fraction in dataset greater than a given value
  
  #permutes non-zero numbers in data; different permutation method
  NEWPERM<-function(x){temp<-x 
                       temp[which(temp!=0|temp!=1)]<-sample(nonzero)
                       temp}  

#ObservedData
  ###Empirical data, for comparison
  otus<-MB_merged_otu_table
    #readRDS("/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MB_merged_otu_table.Rdata")
  #filter by sd or some other measure of variance
  otus <- otus[specnumber(otus) > 1 , ]  #must occur in at least 2 time points, with zero abundance being a real data point in this case 
  nonzero<-otus[which(otus!=0|otus!=1)] #index of non-zero and non-one numbers

  #compute CORRELATION after transposing dataset
  corMB <- cor(t(otus), method = "kendall")
  
  #save as vector, leaving out diagonal
  corMB.vector <- corMB[upper.tri(corMB)]
  
  #save as dataframe and reshape; useful for plotting
  corMB[lower.tri(corMB, T)] <- NA
  corMB <- melt(corMB)%>%
    filter(!is.na(value))
  
#Permutations  
  #Generate scrambled datasets;
  #Note the difference between permuting columns or rows (which just changes their order, and which doesn't do anything in this case, since these are comparisons of pairwise ranked values... the resulting distribution is the same (!) for every such permutation. Here, we're scrambling the contents of the data matrix itself.)

  set.seed(49)
  nPerms = 100
  CorPerms <- lapply(1:nPerms, FUN = function(x){
    PERMFUN(otus)%>%
      as.data.frame%>%
      filter(specnumber(.)>1)%>%
      t%>%
      cor(method = "kendall")%>%
      .[upper.tri(.)]
  })
  beep()

  # #visualize w eCDFs
  #       plot(ecdf(abs(CorPerms[[1]])), col = "lightgrey", xlim=c(0.5,1), ylim=c(0.85, 1))
  #         lapply(1:100, function(x) plot(ecdf(abs(CorPerms[[x]])), add = T, col = "lightgrey"))
  #             plot(ecdf(abs(corMB.vector)), col = "red", add=T)

#Benjamani-Hochberg_FDR
    y<-sapply(1:100, function(x) unlist(CorPerms[[x]]))
                      y<-unlist(y)
                      
                adj.p <- sapply(seq(0.5, 1, 0.005), function(tau) {p.adjust(propObs(y, tau), method = "fdr", n = length(corMB))})     
                
                tmp <- data.frame(
                  Tau = seq(0.5, 1, 0.005),
                  Adjusted.P=adj.p
                )
                
                ggplot(data=tmp, aes(y=Adjusted.P, x=Tau))+
                  geom_smooth()+
                  geom_point()+
                  geom_vline(aes(xintercept = 0.70), color = "red", alpha = 0.5)+
                  geom_hline(aes(yintercept = 0.05), color = "red", alpha = 0.5)
                

                
#pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/Supplemental/Kendall_correlations.pdf",height=6,width=9)
#ggplot(data=tmp, aes(y=Adjusted.P, x=Tau))+
#                  geom_smooth()+
#                  geom_point()+
#                  geom_vline(aes(xintercept = 0.70), color = "red", alpha = 0.5)+
#                  geom_hline(aes(yintercept = 0.05), color = "red", alpha = 0.5)
#dev.off()                
```

```{r strong correlation plots}
gt <- as.character(c("f:Otariidae","f:Carangidae","f:Ellobiopsidae","f:Syndiniaceae","f:Pelagibacteraceae","f:Metridinidae","f:Rhodospirillaceae"))
gt = prune_taxa(gt,MB_all_filt)


foo_gt <-otu_table(gt) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  gather(sample, reads, -rowname) %>% 
  mutate(sample = substr(sample,1,12)) %>% 
  group_by(sample,rowname) %>% 
  summarise(index.mean = mean(reads))
names(foo_gt) <- c("sample","family","index.mean")

tidy.gt<-foo_gt %>% 
  mutate(rn = row_number()) %>% 
  spread(sample, index.mean, fill = 0)
tidy.gt<-tidy.gt[,-2]
tidy.gt <- as.data.frame(tidy.gt)
tidy.gt <- Col2RN(tidy.gt,1)

tidy.gt <-tidy.gt[which(apply(tidy.gt, MARGIN = 1, FUN = function(x) sum(x>0)) > 1),] #filter for taxa occurring more than 3 times in 8 time points

cor.mat.gt <- cor(t(tidy.gt), method = "kendall")
diag(cor.mat.gt)<-0

cor.tidy_gt <- cor.mat.gt %>% 
  as.data.frame %>% 
  rownames_to_column("Fam1") %>% 
  gather(key = Fam2, value = corr, -Fam1) %>% 
  filter(corr > 0)
strongCorrs_gt <- unique(unlist(cor.tidy_gt[,1:2]))  #which families have really strong correlations?

heatmap.2(abs(cor.mat.gt[strongCorrs_gt, strongCorrs_gt]),dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')

z_gt <- t(tidy.gt[strongCorrs_gt,])
trophicLevels = trophic$trophic_fv[match(colnames(z_gt), trophic$taxa)]
z_gt <- z_gt[,order(trophicLevels)]  #reorder by trophic level

#source("/Volumes/GoogleDrive/Team Drives/m2w_analysis/analysis/strongCorrsPlot.R")
pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/grey_strongCor.pdf", width = 10, height = 10)
strong.corrs.plot(z_gt, cutoff = 0.6)
dev.off()

############### BLUE ###########

bt <- as.character(c("f:Gonyaulacaceae","f:Prorocentraceae","f:Chrysolepidomonadaceae","f:Urechidae","f:Balaenopteridae","f:Sugiuridae","f:Rathkeidae","f:Puniceicoccaceae","f:Listeriaceae","f:Euphausiidae","f:Pleurotaceae"))
bt = prune_taxa(bt,MB_all_filt)


foo <-otu_table(bt) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  gather(sample, reads, -rowname) %>% 
  mutate(sample = substr(sample,1,12)) %>% 
  group_by(sample,rowname) %>% 
  summarise(index.mean = mean(reads))
names(foo) <- c("sample","family","index.mean")

tidy.blue<-foo %>% 
  mutate(rn = row_number()) %>% 
  spread(sample, index.mean, fill = 0)
tidy.blue<-tidy.blue[,-2]
tidy.blue <- as.data.frame(tidy.blue)
tidy.blue <- Col2RN(tidy.blue,1)

tidy.blue <-tidy.blue[which(apply(tidy.blue, MARGIN = 1, FUN = function(x) sum(x>0)) > 1),] #filter for taxa occurring more than 3 times in 8 time points

cor.mat.blue <- cor(t(tidy.blue), method = "kendall")
diag(cor.mat.blue)<-0

cor.tidy <- cor.mat.blue %>% 
  as.data.frame %>% 
  rownames_to_column("Fam1") %>% 
  gather(key = Fam2, value = corr, -Fam1) %>% 
  filter(corr > 0)
strongCorrs <- unique(unlist(cor.tidy[,1:2]))  #which families have really strong correlations?

heatmap.2(abs(cor.mat.blue[strongCorrs, strongCorrs]),dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')

z <- t(tidy.blue[strongCorrs,])
trophicLevels = trophic$trophic_fv[match(colnames(z), trophic$taxa)]
z <- z[,order(trophicLevels)]  #reorder by trophic level

#source("/Volumes/GoogleDrive/Team Drives/m2w_analysis/analysis/strongCorrsPlot.R")
pdf("/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/blue_stronCor.pdf", width = 10, height = 10)
strong.corrs.plot(z, cutoff = 0.6)
dev.off()

```

```{r connection of all networks with environmental variable}
con <- intramodularConnectivity.fromExpr(datExpr_MB, moduleColors_MB, 
                                         corFnc = "cor", corOptions = "use = 'p'",
                                         weights = NULL,
                                         distFnc = "dist", distOptions = "method = 'euclidean'",
                                         networkType = "unsigned", power = 8,
                                         scaleByMax = FALSE,
                                         ignoreColors = if (is.numeric(colors)) 0 else "grey",
                                         getWholeNetworkConnectivity = TRUE)


con$taxa <- rownames(t(datExpr_MB))
#blue_MB <- blue_MB[,1]
con_blue <- con[con$taxa %in% blue_MB, ]
write.csv(con_blue, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_blue.csv")
trophic_lev <- read.csv(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/subnetxtrophic_ordered_20181112.csv")
con_blue$trophic_lev <- trophic_lev$trophic_fv[match(con_blue$taxa, trophic_lev$taxa)]

#dg_MB <- dg_MB[,1]
con_dg <- con[con$taxa %in% dg_MB, ]
write.csv(con_dg, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_dg.csv")
con_dg$trophic_lev <- trophic_lev$trophic_fv[match(con_dg$taxa, trophic_lev$taxa)]

con_green <- con[con$taxa %in% green_MB, ]
#write.csv(con_dg, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_dg.csv")
con_green$trophic_lev <- trophic_lev$trophic_fv[match(con_green$taxa, trophic_lev$taxa)]

con_yel <- con[con$taxa %in% yel_MB, ]
#write.csv(con_dg, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_dg.csv")
con_yel$trophic_lev <- trophic_lev$trophic_fv[match(con_yel$taxa, trophic_lev$taxa)]

con_orange <- con[con$taxa %in% orange_MB, ]
#write.csv(con_orange, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_orange.csv")
con_orange$trophic_lev <- trophic_lev$trophic_fv[match(con_orange$taxa, trophic_lev$taxa)]

con_grey <- con[con$taxa %in% grey_MB, ]
#write.csv(con_dg, file = "/Volumes/GoogleDrive/Team Drives/m2w_analysis/data/MEGAN6/post_decontam/MB/con_dg.csv")
con_grey$trophic_lev <- trophic_lev$trophic_fv[match(con_grey$taxa, trophic_lev$taxa)]

#Blue and grey separately!
datExpr_MB_Blue <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% blue_MB)
datExpr_MB_grey <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% dg_MB)
datExpr_MB_green <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% green_MB)
datExpr_MB_yel <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% yel_MB)
datExpr_MB_orange <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% orange_MB)
datExpr_MB_black <- subset(datExpr_MB_t,rownames(datExpr_MB_t) %in% grey_MB)

cor_blue <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_Blue)),meta, method = "pearson")))
cor_dg <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_grey)),meta, method = "pearson")))
cor_green <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_green)),meta, method = "pearson")))
cor_yel <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_yel)),meta, method = "pearson")))
cor_orange <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_orange)),meta, method = "pearson")))
cor_black <- as.data.frame(abs(cor(as.matrix(t(datExpr_MB_black)),meta, method = "pearson")))


pdf(file="/Volumes/GoogleDrive/Team Drives/m2w_analysis/plots/con_cor_env_all.pdf", height=25, width=25)
par(mfrow=c(6,6))

plot(cor_blue$upwelling,con_blue$kWithin)
plot(cor_blue$temp,con_blue$kWithin)
plot(cor_blue$salinity,con_blue$kWithin)
plot(cor_blue$chlorophyll,con_blue$kWithin)
plot(cor_blue$nitrate,con_blue$kWithin)
plot(cor_blue$diss_oxygen,con_blue$kWithin)

plot(cor_dg$upwelling,con_dg$kWithin)
plot(cor_dg$temp,con_dg$kWithin)
plot(cor_dg$salinity,con_dg$kWithin)
plot(cor_dg$chlorophyll,con_dg$kWithin)
plot(cor_dg$nitrate,con_dg$kWithin)
plot(cor_dg$diss_oxygen,con_dg$kWithin)

plot(cor_green$upwelling,con_green$kWithin)
plot(cor_green$temp,con_green$kWithin)
plot(cor_green$salinity,con_green$kWithin)
plot(cor_green$chlorophyll,con_green$kWithin)
plot(cor_green$nitrate,con_green$kWithin)
plot(cor_green$diss_oxygen,con_green$kWithin)

plot(cor_yel$upwelling,con_yel$kWithin)
plot(cor_yel$temp,con_yel$kWithin)
plot(cor_yel$salinity,con_yel$kWithin)
plot(cor_yel$chlorophyll,con_yel$kWithin)
plot(cor_yel$nitrate,con_yel$kWithin)
plot(cor_yel$diss_oxygen,con_yel$kWithin)

plot(cor_orange$upwelling,con_orange$kWithin)
plot(cor_orange$temp,con_orange$kWithin)
plot(cor_orange$salinity,con_orange$kWithin)
plot(cor_orange$chlorophyll,con_orange$kTotal)
plot(cor_orange$nitrate,con_orange$kWithin)
plot(cor_orange$diss_oxygen,con_orange$kWithin)

plot(cor_black$upwelling,con_grey$kWithin)
plot(cor_black$temp,con_grey$kWithin)
plot(cor_black$salinity,con_grey$kWithin)
plot(cor_black$chlorophyll,con_grey$kWithin)
plot(cor_black$nitrate,con_grey$kWithin)
plot(cor_black$diss_oxygen,con_grey$kWithin)

dev.off()

```

