---
title: "Richness of 16S, 18S, COI, and 12S"
author: "Anni Djurhuus"
date: "15 August 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read biom file 18S and 12S,echo=FALSE}
#biocLite("phyloseq")
library(phyloseq)
#16S
#m2w_16S <- import_biom("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/16S/")
#m2w_16S <- subset_samples(m2w_16S, sample_type == "environmental")
#metadata_16S <- m2w_16S@sam_data
#otu_16S <- otu_table(m2w_16S, taxa_are_rows=TRUE)
#18S
m2w_18S <- import_biom("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/18S/M2W_18S_80per_NT_json_obs_md.biom")
m2w_18S <- subset_samples(m2w_18S, sample_type == "environmental")
metadata_18S <- m2w_18S@sam_data
otu_18S <- otu_table(m2w_18S, taxa_are_rows=TRUE)
b <- as.data.frame(otu_18S)
tax_18S <- tax_table(m2w_18S)
#12S
m2w_COI <- import_biom("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/COI/COI_m2w_twostep_json_obs_md.biom")
m2w_COI <- subset_samples(m2w_COI, sample_type == "environmental")
m2w_COI <- subset_samples(m2w_COI, DEPTH_M == 0)
metadata_COI <- m2w_COI@sam_data
otu_COI <- otu_table(m2w_COI, taxa_are_rows=TRUE)
#12S
m2w_12S <- import_biom("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/12S/m2w_12S_MB_20170815_json_obs_md.biom")
m2w_12S <- subset_samples(m2w_12S, sample_names(m2w_12S) != "ArtComm_HS_1" & sample_names(m2w_12S) != "ArtComm_HS_2" & sample_names(m2w_12S) !="ArtComm_HS_3" & sample_names(m2w_12S) !="CB_CANON160925_1" & sample_names(m2w_12S) !="CB_CANON160925_2" & sample_names(m2w_12S) !="CB_CANON160925_3" & sample_names(m2w_12S) !="EB_11.16.16" & sample_names(m2w_12S) !="EB_11.21.16" & sample_names(m2w_12S) !="EB_12.28.16" & sample_names(m2w_12S) !="NTC_pool_1" & sample_names(m2w_12S) !="NTC_pool_2" & sample_names(m2w_12S) !="NTC_pool_3")
#m2w_12S <- subset_samples(m2w_12S, sample_type == "environmental")
otu_12S <- otu_table(m2w_12S, taxa_are_rows=TRUE)
metadata_12S <- m2w_12S@sam_data
#names(metadata_12S)
```

#plot richness for 12S, COI, and 18S of raw sequences
```{r Plot richness for 12S and 18S}
#install.packages("cowplot")
require(cowplot)
#p <- plot_richness(m2w_16S,x="DATE_TIME_GMT",title="16S",measures = "Observed") + theme(axis.title.x=element_blank())
#p <- p + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
#p <- p + geom_boxplot(outlier.color = NA, fill=NA)
#p + geom_point(size=5, alpha=0.4)

p1 <- plot_richness(m2w_18S,x="DATE_TIME_GMT",title="18S",measures = "Observed") + theme(axis.title.x=element_blank())
p1 <- p1 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p1 <- p1 + geom_boxplot(outlier.color = NA, fill=NA)
p1 + geom_point(size=5, alpha=0.4)

p2 <- plot_richness(m2w_COI,x="DATE_TIME_GMT",title="COI",measures = "Observed") + theme(axis.title.x=element_blank())
p2 <- p2 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p2 <- p2 + geom_boxplot(outlier.color = NA, fill=NA)
p2 + geom_point(size=5, alpha=0.4)

p3 <- plot_richness(m2w_12S,x="DATE_TIME_GMT",title="12S",measures = "Observed") + theme(axis.title.x=element_blank())
p3 <- p3 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p3 <- p3 + geom_boxplot(outlier.color = NA, fill=NA)
p3 + geom_point(size=5, alpha=0.4)
#plot_grid(p1, p2, p3, labels = c("A", "B", "C"), align="h")
```

####Number of sequences per sample
```{r rarefy sequences}
#colSums(otu_16S)
colSums(otu_18S)
colSums(otu_COI)
colSums(otu_12S)

#rare_16S = rarefy_even_depth(m2w_16S)
rare_18S = rarefy_even_depth(m2w_18S)
rare_COI = rarefy_even_depth(m2w_COI)
rare_12S = rarefy_even_depth(m2w_12S)

```

#plots of richness post rarefaction
```{r Plot richness for 12S and 18S post rarefication,echo=FALSE}
#install.packages("cowplot")
require(cowplot)
#p4 <- plot_richness(rare_16S,x="DATE_TIME_GMT",title="16S",measures = "Observed") + theme(axis.title.x=element_blank())
#p4 <- p4 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
#p4 <- p4 + geom_boxplot(outlier.color = NA, fill=NA)
#p4 + geom_point(size=5, alpha=0.4)

p5 <- plot_richness(rare_18S,x="DATE_TIME_GMT",title="18S",measures = "Observed") + theme(axis.title.x=element_blank())
p5 <- p5 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p5 <- p5 + geom_boxplot(outlier.color = NA, fill=NA)
p5 + geom_point(size=5, alpha=0.4)
 
p6 <- plot_richness(rare_COI,x="DATE_TIME_GMT",title="COI",measures = "Observed") + theme(axis.title.x=element_blank())
p6 <- p6 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p6 <- p6 + geom_boxplot(outlier.color = NA, fill=NA)
p6 + geom_point(size=5, alpha=0.4)

p7 <- plot_richness(m2w_12S,x="DATE_TIME_GMT",title="12S",measures = "Observed") + theme(axis.title.x=element_blank())
p7 <- p7 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
p7 <- p7 + geom_boxplot(outlier.color = NA, fill=NA)
p7 + geom_point(size=5, alpha=0.4)
```


#DESeq2
```{r DESeq2}
library(DESeq2)
#16S
#deseq_18s = phyloseq_to_deseq2(m2w_18S, ~ DATE_TIME_GMT)
#deseq_18s = DESeq(deseq_18s, test="Wald", fitType="parametric")
#deseq_18s = estimateSizeFactors(deseq_18s)
#deseq_18s <- counts(deseq_18s, normalized=TRUE)
#m2w_18S2 <- otu_table(deseq_18s, taxa_are_rows = TRUE)

#18S
deseq_18s = phyloseq_to_deseq2(m2w_18S, ~ DATE_TIME_GMT)
deseq_18s = DESeq(deseq_18s, test="Wald", fitType="parametric")

res = results(deseq_18s, cooksCutoff = FALSE)
alpha = 0.01
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(m2w_18S)[rownames(sigtab), ], "matrix"))
head(sigtab)

library("ggplot2")
theme_set(theme_bw())
scale_fill_discrete <- function(palname = "Set1", ...) {
    scale_fill_brewer(palette = palname, ...)
}
# Phylum order
x = tapply(sigtab$log2FoldChange, sigtab$Rank1, function(x) max(x))
x = sort(x, TRUE)
sigtab$Rank1 = factor(as.character(sigtab$Rank1), levels=names(x))
# Genus order
x = tapply(sigtab$log2FoldChange, sigtab$Rank6, function(x) max(x))
x = sort(x, TRUE)
sigtab$Rank6 = factor(as.character(sigtab$Rank6), levels=names(x))
ggplot(sigtab, aes(x=Rank6, y=log2FoldChange, color=Rank1)) + geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))


deseq_18s = estimateSizeFactors(deseq_18s)
deseq_18s <- counts(deseq_18s, normalized=TRUE)
a <- as.data.frame(deseq_18s)
otu2_18S <- otu_table(deseq_18s, taxa_are_rows = TRUE)
m2w_18S2 <- merge_phyloseq(metadata_18S,otu2_18S,tax_18S)


#COI
#deseq_COI = phyloseq_to_deseq2(m2w_COI, ~ DATE_TIME_GMT)
# deseq_COI = DESeq(deseq_COI, test="Wald", fitType="parametric")
# deseq_COI = estimateSizeFactors(deseq_COI)
# deseq_COI <- counts(deseq_COI, normalized=TRUE)
# m2w_18S2 <- otu_table(deseq_COI, taxa_are_rows = TRUE)
# 
# #12S
# #18S
# deseq_12s = phyloseq_to_deseq2(m2w_12S, ~ DATE_TIME_GMT)
# deseq_12s = DESeq(deseq_12s, test="Wald", fitType="parametric")
# deseq_12s = estimateSizeFactors(deseq_12s)
# deseq_12s <- counts(deseq_12s, normalized=TRUE)
# m2w_12S2 <- otu_table(deseq_12s, taxa_are_rows = TRUE)

```

```{r plots of richness post DESeq2}
#p8 <- plot_richness(m2w_18S2,x="DATE_TIME_GMT",title="18S",measures = "Observed") + theme(axis.title.x=element_blank())
#p8 <- p8 + geom_point(size=5, alpha=0.4,position=position_jitter(width=0.1))
#p8 <- p8 + geom_boxplot(outlier.color = NA, fill=NA)
#p8 + geom_point(size=5, alpha=0.4)

# #plot_grid(p3, p4, p5, labels = c("A", "B", "C"),align="h")

```


#Compare all
```{r}
#plot_grid(p1, p5)
#, labels = c("A", "B"),align="h", nrow=2)
#plot_grid(p2, p6, labels = c("A", "B"),align="h", nrow=2)
#plot_grid(p3, p7, labels = c("A", "B"),align="h", nrow=2)
```



#```{r richness post rarefication and occupancy}
#load("/Users/anni_djurhuus/Documents/Projects/MBON/m2w/18S/OccData18s_COI_rarefied.Rdata")
#```

